import Ciencia from "./assets/ciencia.png";
import Deportes from "./assets/deportes.png";
import Filosofia from "./assets/filosofía.png";
import Geografia from "./assets/geografía.png";
import Historia from "./assets/historia.png";
import Literatura from "./assets/literatura.png";
import Tecnologia from "./assets/tecnología.png";
import SymbolsOfVenezuela from "./assets/symbolsofvenezuela.png";
import VenezuelanFoodsAndFlavors from "./assets/venezuelanfoodsandflavors.png";
import PlacesAndCitiesOfVenezuela from "./assets/placesandcitiesofvenezuela.png";
import CharactersAndPopularCulture from "./assets/charactersandpopularculture.png";

export const imgs = [
  Ciencia,
  Deportes,
  Filosofia,
  Geografia,
  Historia,
  Literatura,
  Tecnologia,
  SymbolsOfVenezuela,
  VenezuelanFoodsAndFlavors,
  PlacesAndCitiesOfVenezuela,
  CharactersAndPopularCulture,
];

export const categories = {
  historia: "Historia",
  literatura: "Literatura",
  deportes: "Deportes",
  ciencia: "Ciencia",
  filosofia: "Filosofía",
  tecnologia: "Tecnología",
  geografia: "Geografía",
  symbolsOfVenezuela: "Symbols of Venezuela",
  venezuelanFoodsAndFlavors: "Venezuelan Foods and Flavors",
  placesAndCitiesOfVenezuela: "Places and Cities of Venezuela",
  charactersAndPopularCulture: "Characters and Popular Culture",
};

const {
  historia,
  tecnologia,
  literatura,
  deportes,
  ciencia,
  filosofia,
  geografia,
  symbolsOfVenezuela,
  venezuelanFoodsAndFlavors,
  placesAndCitiesOfVenezuela,
  charactersAndPopularCulture,
} = categories;

export const categoryImages = {
  // usa las cadenas visibles (los valores de categories) como keys,
  // así puedes buscarlas directamente con el param `category`
  [categories.historia]: Historia, // si tienes la import Historia arriba
  [categories.literatura]: Literatura,
  [categories.deportes]: Deportes,
  [categories.ciencia]: Ciencia,
  [categories.filosofia]: Filosofia,
  [categories.tecnologia]: Tecnologia,
  [categories.geografia]: Geografia,
  [categories.symbolsOfVenezuela]: SymbolsOfVenezuela,
  [categories.venezuelanFoodsAndFlavors]: VenezuelanFoodsAndFlavors,
  [categories.placesAndCitiesOfVenezuela]: PlacesAndCitiesOfVenezuela,
  [categories.charactersAndPopularCulture]: CharactersAndPopularCulture,
};

export const questions = [
  {
    id: 1,
    difficulty: "Easy",
    question: "What are the colors of the Venezuelan flag?",
    category: symbolsOfVenezuela,
    correct_answer: "Yellow, blue and red",
    incorrect_answers: [
      "Green, white and red",
      "Blue, white and red",
      "Black, yellow and red",
    ],
  },
  {
    id: 2,
    difficulty: "Easy",
    question: "What is the national anthem of Venezuela (a national symbol)?",
    category: symbolsOfVenezuela,
    correct_answer: "The National Anthem",
    incorrect_answers: [
      "La Marcha Real",
      "La Marseillaise",
      "God Save the King",
    ],
  },
  {
    id: 3,
    difficulty: "Easy",
    question: "What is the national bird of Venezuela?",
    category: symbolsOfVenezuela,
    correct_answer: "Turpial",
    incorrect_answers: ["Quetzal", "Condor", "Guanabana"],
  },
  {
    id: 4,
    difficulty: "Easy",
    question: "What is the national tree of Venezuela?",
    category: symbolsOfVenezuela,
    correct_answer: "Araguaney",
    incorrect_answers: ["Ceiba", "Quebracho", "Palo santo"],
  },
  {
    id: 5,
    difficulty: "Easy",
    question: "What is the national flower of Venezuela (Cattleya mossiae)?",
    category: symbolsOfVenezuela,
    correct_answer: "Orchid",
    incorrect_answers: ["Rose", "Sunflower", "Lily"],
  },
  {
    id: 6,
    difficulty: "Easy",
    question: "What is the official currency of Venezuela?",
    category: symbolsOfVenezuela,
    correct_answer: "Bolívar",
    incorrect_answers: ["Peso", "Canadian Dollar", "Real"],
  },
  {
    id: 7,
    difficulty: "Easy",
    question: "Which famous Venezuelan waterfall is the highest in the world?",
    category: symbolsOfVenezuela,
    correct_answer: "Angel Falls",
    incorrect_answers: ["Niagara Falls", "Iguazu Falls", "Victoria Falls"],
  },
  {
    id: 8,
    difficulty: "Easy",
    question:
      "How many stars are there on the Venezuelan flag (commonly seen current version)?",
    category: symbolsOfVenezuela,
    correct_answer: "8",
    incorrect_answers: ["7", "9", "6"],
  },
  {
    id: 9,
    difficulty: "Easy",
    question: "What appears in the center of the Venezuelan coat of arms?",
    category: symbolsOfVenezuela,
    correct_answer: "A horse and agricultural elements",
    incorrect_answers: [
      "A tower and a lion",
      "A dove with a branch",
      "A lighthouse and an anchor",
    ],
  },
  {
    id: 10,
    difficulty: "Easy",
    question: "What is an important national holiday in Venezuela?",
    category: symbolsOfVenezuela,
    correct_answer: "5th of July (Declaration of Independence)",
    incorrect_answers: ["4th of July", "May 1st", "12th of October"],
  },
  {
    id: 11,
    difficulty: "Easy",
    question: "What is an arepa?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "A flat cornmeal cake",
    incorrect_answers: ["A fish soup", "A milk dessert", "A meat empanada"],
  },
  {
    id: 12,
    difficulty: "Easy",
    question:
      "Which traditional dish combines shredded meat, rice, black beans, and plantain?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Pabellón criollo",
    incorrect_answers: ["Sancocho", "Feijoada", "Paella"],
  },
  {
    id: 13,
    difficulty: "Easy",
    question: "Which typical Venezuelan sweet is made with raw sugar and lime?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Papelón con limón",
    incorrect_answers: ["Marzipan", "Tres leches", "Churros"],
  },
  {
    id: 14,
    difficulty: "Easy",
    question: "What are tequeños?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Cheese sticks wrapped in fried dough",
    incorrect_answers: [
      "A type of sweet arepa",
      "Saltine cookies",
      "A coconut dessert",
    ],
  },
  {
    id: 15,
    difficulty: "Easy",
    question:
      "Which Venezuelan food is traditionally prepared in December and is typical at Christmas?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Hallaca",
    incorrect_answers: ["Mexican tamales", "Sushi", "Poutine"],
  },
  {
    id: 16,
    difficulty: "Easy",
    question:
      "What is the name of the sweet corn cake often eaten in Venezuela?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Cachapa",
    incorrect_answers: ["Arequipe", "Buñuelo", "Yuca empanada"],
  },
  {
    id: 17,
    difficulty: "Easy",
    question:
      "Which cold, fermented corn-based beverage is popular in Venezuela?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Chicha",
    incorrect_answers: ["Kefir", "Sake", "Kombucha"],
  },
  {
    id: 18,
    difficulty: "Easy",
    question: "Which Venezuelan dessert is made with green papaya and panela?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Dulce de lechosa",
    incorrect_answers: ["Quesillo", "Tres leches", "Bienmesabe"],
  },
  {
    id: 19,
    difficulty: "Easy",
    question: "What is a very common arepa filling in Venezuela?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Shredded beef",
    incorrect_answers: ["Salmon sashimi", "Pesto pasta", "Seaweed croquettes"],
  },
  {
    id: 20,
    difficulty: "Easy",
    question:
      "Which typical Venezuelan food is a fried corn empanada very popular on the streets?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Venezuelan empanada",
    incorrect_answers: ["Samosa", "French crepe", "Dumpling"],
  },
  {
    id: 21,
    difficulty: "Easy",
    question: "What is the capital of Venezuela?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Caracas",
    incorrect_answers: ["Maracaibo", "Valencia", "Mérida"],
  },
  {
    id: 22,
    difficulty: "Easy",
    question: "Which Venezuelan city is located next to Lake Maracaibo?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Maracaibo",
    incorrect_answers: ["Puerto Ordaz", "Porlamar", "Maturín"],
  },
  {
    id: 23,
    difficulty: "Easy",
    question:
      "In which state is the city of Mérida located, famous for its mountains?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Mérida",
    incorrect_answers: ["Zulia", "Anzoátegui", "Delta Amacuro"],
  },
  {
    id: 24,
    difficulty: "Easy",
    question:
      "Which Venezuelan island is famous for its beaches and also called 'Isla de Margarita'?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Margarita",
    incorrect_answers: ["Coche", "Bonaire", "Curaçao"],
  },
  {
    id: 25,
    difficulty: "Easy",
    question:
      "Which Venezuelan region is known for Angel Falls and the Gran Sabana?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Guayana (Bolívar state)",
    incorrect_answers: ["Los Llanos", "Andes", "Eastern Coast of the Lake"],
  },
  {
    id: 26,
    difficulty: "Easy",
    question:
      "Which major port is located in Anzoátegui state, known for its maritime activity?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Puerto La Cruz",
    incorrect_answers: ["La Guaira", "Puerto Cabello", "Punta Cardón"],
  },
  {
    id: 27,
    difficulty: "Easy",
    question: "What is the capital of Zulia state?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Maracaibo",
    incorrect_answers: ["Cabimas", "San Cristóbal", "Barquisimeto"],
  },
  {
    id: 28,
    difficulty: "Easy",
    question:
      "Which Venezuelan city is known for its important industry and is in the center of the country (Carabobo state)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Valencia",
    incorrect_answers: ["Ciudad Bolívar", "Puerto Ordaz", "Cumana"],
  },
  {
    id: 29,
    difficulty: "Easy",
    question: "What is the capital city of Lara state?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Barquisimeto",
    incorrect_answers: ["Valera", "Porlamar", "San Juan de los Morros"],
  },
  {
    id: 30,
    difficulty: "Easy",
    question:
      "Which city is famous for its cable car and Andean mountains (Mérida state)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Mérida",
    incorrect_answers: ["La Guaira", "Maracay", "Coro"],
  },
  {
    id: 31,
    difficulty: "Easy",
    question:
      "Which professional baseball team from Caracas is very well-known in Venezuela?",
    category: charactersAndPopularCulture,
    correct_answer: "Leones del Caracas",
    incorrect_answers: [
      "Tiburones de La Guaira",
      "Magallanes",
      "Bravos de Margarita",
    ],
  },
  {
    id: 32,
    difficulty: "Easy",
    question:
      "Who is a Venezuelan singer famous for salsa and the song 'Llorarás'?",
    category: charactersAndPopularCulture,
    correct_answer: "Oscar D'León",
    incorrect_answers: ["Ricky Martin", "Marc Anthony", "Carlos Vives"],
  },
  {
    id: 33,
    difficulty: "Easy",
    question:
      "Which Venezuelan pianist and composer is famous for traditional music and folk songs (e.g. 'Caballo Viejo')?",
    category: charactersAndPopularCulture,
    correct_answer: "Simón Díaz",
    incorrect_answers: ["Juanes", "Shakira", "Plácido Domingo"],
  },
  {
    id: 34,
    difficulty: "Easy",
    question:
      "Which Venezuelan athlete won medals in triple jump (famous at international events)?",
    category: charactersAndPopularCulture,
    correct_answer: "Yulimar Rojas",
    incorrect_answers: ["Maria Sharapova", "Usain Bolt", "Carl Lewis"],
  },
  {
    id: 35,
    difficulty: "Easy",
    question:
      "Which Venezuelan conductor is internationally recognized (former conductor of Los Angeles Philharmonic)?",
    category: charactersAndPopularCulture,
    correct_answer: "Gustavo Dudamel",
    incorrect_answers: [
      "Zubin Mehta",
      "Herbert von Karajan",
      "Leonard Bernstein",
    ],
  },
  {
    id: 36,
    difficulty: "Easy",
    question:
      "What Venezuelan comedy show was very popular for decades and featured comic sketches?",
    category: charactersAndPopularCulture,
    correct_answer: "Radio Rochela",
    incorrect_answers: [
      "Saturday Night Live",
      "Monty Python",
      "El Chavo del 8",
    ],
  },
  {
    id: 37,
    difficulty: "Easy",
    question:
      "What is the name of the traditional Venezuelan llanero dance that uses harp, cuatro, and maracas?",
    category: charactersAndPopularCulture,
    correct_answer: "Joropo",
    incorrect_answers: ["Tango", "Samba", "Reggaeton"],
  },
  {
    id: 38,
    difficulty: "Easy",
    question: "Which of these dishes has inspired Venezuelan folk music?",
    category: charactersAndPopularCulture,
    correct_answer: "Pabellón criollo",
    incorrect_answers: ["Sushi", "Pizza", "Curry"],
  },
  {
    id: 39,
    difficulty: "Easy",
    question:
      "Which four-string musical instrument is typical in Venezuelan music?",
    category: charactersAndPopularCulture,
    correct_answer: "Cuatro",
    incorrect_answers: ["Electric guitar", "Violin", "Sitar"],
  },
  {
    id: 40,
    difficulty: "Easy",
    question:
      "Which fair or popular festival is celebrated in many Venezuelan cities with music and parades (e.g. at Carnaval)?",
    category: charactersAndPopularCulture,
    correct_answer: "Carnival",
    incorrect_answers: ["Oktoberfest", "Thanksgiving", "Diwali"],
  },
  {
    id: 41,
    difficulty: "Easy",
    question:
      "Which fruit is very typical in Venezuela and is used to make juices and desserts (yellow and sweet)?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Mango",
    incorrect_answers: ["Apple", "Blueberry", "Raspberry"],
  },
  {
    id: 42,
    difficulty: "Easy",
    question:
      "What is the name of the typical Venezuelan meat and vegetable soup often cooked on weekends?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Sancocho",
    incorrect_answers: ["Miso", "Gazpacho", "Borscht"],
  },
  {
    id: 43,
    difficulty: "Easy",
    question:
      "What kind of soft, fresh cheese is commonly used as a side for arepas and cachapas?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Fresh white cheese",
    incorrect_answers: ["Gorgonzola", "Aged cheddar", "Roquefort"],
  },
  {
    id: 44,
    difficulty: "Easy",
    question:
      "What cereal grain is used to make Venezuelan arepas and empanadas?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Precooked corn flour",
    incorrect_answers: ["Wheat flour", "Rice flour", "Oat flour"],
  },
  {
    id: 45,
    difficulty: "Easy",
    question:
      "Which traditional hot drink made with cocoa or chocolate is common on Venezuelan mornings?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Hot chocolate",
    incorrect_answers: ["Matcha tea", "Turkish coffee", "Kopi luwak"],
  },
  {
    id: 46,
    difficulty: "Easy",
    question: "Which refreshing drink is made with grated raw sugar and lime?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Sugarcane lemonade (Agua de papelón con limón)",
    incorrect_answers: ["Milk lemonade", "Peach iced tea", "Tamarind soda"],
  },
  {
    id: 47,
    difficulty: "Easy",
    question:
      "Which seafood is popular on the Venezuelan coast and in seafood arepas or empanadas?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Shrimp",
    incorrect_answers: ["Giant crab", "Eel", "Freshwater trout"],
  },
  {
    id: 48,
    difficulty: "Easy",
    question:
      "What kind of round, flattened bread is used in Venezuela as a base for many fillings?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Arepa",
    incorrect_answers: ["Baguette", "Ciabatta", "Naan"],
  },
  {
    id: 49,
    difficulty: "Easy",
    question:
      "Which tropical fruit is used to make the popular dessert 'dulce de lechosa'?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Green papaya",
    incorrect_answers: ["Banana", "Apple", "Cherry"],
  },
  {
    id: 50,
    difficulty: "Easy",
    question:
      "Which sweet, creamy dairy product is widely consumed as a dessert in Venezuela (similar to flan)?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Quesillo",
    incorrect_answers: ["Panna cotta", "Baklava", "Tiramisu"],
  },
  {
    id: 51,
    difficulty: "Easy",
    question:
      "What is the administrative capital of Miranda state and a city near Caracas?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Los Teques",
    incorrect_answers: ["La Victoria", "Ciudad Bolívar", "Punto Fijo"],
  },
  {
    id: 52,
    difficulty: "Easy",
    question:
      "Which Venezuelan peninsula is known for its beaches and the Morrocoy National Park?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Peninsula de Paraguaná",
    incorrect_answers: [
      "Yucatán Peninsula",
      "Iberian Peninsula",
      "Kola Peninsula",
    ],
  },
  {
    id: 53,
    difficulty: "Easy",
    question:
      "Which important Venezuelan port is north of Caracas and serves the capital (Vargas/La Guaira state)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "La Guaira",
    incorrect_answers: ["Puerto Madryn", "Puerto Montt", "Puerto Varas"],
  },
  {
    id: 54,
    difficulty: "Easy",
    question:
      "In which state is the Paraguaná Peninsula (known for beaches and refineries)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Falcón",
    incorrect_answers: ["Nueva Esparta", "Monagas", "Amazonas"],
  },
  {
    id: 55,
    difficulty: "Easy",
    question:
      "Which port city is in the west of the country and is an oil industry hub (Zulia state)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Maracaibo",
    incorrect_answers: ["Maturín", "Barcelona", "Valera"],
  },
  {
    id: 56,
    difficulty: "Easy",
    question:
      "Which Venezuelan state is known for its plains and cattle ranching, famous in llanero music?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Lara/Los Llanos (e.g., Guárico or Apure state)",
    incorrect_answers: ["Andean Mérida", "Insular Sucre", "Mountainous Zulia"],
  },
  {
    id: 57,
    difficulty: "Easy",
    question:
      "Which city is known for its colonial history and well-preserved colonial center (Falcón state)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Coro",
    incorrect_answers: ["Puerto Ordaz", "Maracay", "San Felipe"],
  },
  {
    id: 58,
    difficulty: "Easy",
    question:
      "Which tourist city in eastern Venezuela is famous for beaches and nightlife (Nueva Esparta state)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Porlamar (Isla de Margarita)",
    incorrect_answers: ["Cumaná", "Maturín", "San Cristóbal"],
  },
  {
    id: 59,
    difficulty: "Easy",
    question:
      "Which city is at the confluence of the Orinoco and Caroní Rivers and is part of the Guayana industrial zone?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Ciudad Guayana / Puerto Ordaz",
    incorrect_answers: ["Maracay", "Valencia", "Los Teques"],
  },
  {
    id: 60,
    difficulty: "Easy",
    question:
      "Which region of Venezuela is famous for its landscape of tepuis and plateaus (such as Auyán-tepui)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "La Gran Sabana (Guayana)",
    incorrect_answers: ["Los Llanos", "Andes Mountains", "Eastern Coast"],
  },
  {
    id: 61,
    difficulty: "Easy",
    question:
      "Which famous Venezuelan ballplayer plays in the Major Leagues and is known for being short in stature but very skilled (popular player)?",
    category: charactersAndPopularCulture,
    correct_answer: "José Altuve",
    incorrect_answers: ["Cristiano Ronaldo", "LeBron James", "Lionel Messi"],
  },
  {
    id: 62,
    difficulty: "Easy",
    question:
      "Which singer born in Venezuela is known for ballads and international hits (Montaner family)?",
    category: charactersAndPopularCulture,
    correct_answer: "Ricardo Montaner",
    incorrect_answers: ["Shakira", "Enrique Iglesias", "Luis Fonsi"],
  },
  {
    id: 63,
    difficulty: "Easy",
    question:
      "Which Venezuelan TV host or figure is famous for classic children's shows (historical figure)?",
    category: charactersAndPopularCulture,
    correct_answer: "Renny Ottolina (historical TV figure)",
    incorrect_answers: ["Bill Cosby", "David Letterman", "Conan O'Brien"],
  },
  {
    id: 64,
    difficulty: "Easy",
    question:
      "What sport is considered the most popular in Venezuela alongside baseball?",
    category: charactersAndPopularCulture,
    correct_answer: "Soccer (Football)",
    incorrect_answers: ["Ice hockey", "Curling", "Cricket"],
  },
  {
    id: 65,
    difficulty: "Easy",
    question:
      "What is the famous Venezuelan musical genre that uses harp, cuatro, and maracas?",
    category: charactersAndPopularCulture,
    correct_answer: "Joropo",
    incorrect_answers: ["Reggae", "Reggaeton", "K-pop"],
  },
  {
    id: 66,
    difficulty: "Easy",
    question: "Which Venezuelan literary figure wrote 'Doña Bárbara'?",
    category: charactersAndPopularCulture,
    correct_answer: "Rómulo Gallegos",
    incorrect_answers: [
      "Gabriel García Márquez",
      "Pablo Neruda",
      "Isabel Allende",
    ],
  },
  {
    id: 67,
    difficulty: "Easy",
    question:
      "Which music or dance festival is typical in many regions of Venezuela during patron saint celebrations?",
    category: charactersAndPopularCulture,
    correct_answer: "Comparsas and parrandas",
    incorrect_answers: ["La Tomatina", "Oktoberfest", "Diwali"],
  },
  {
    id: 68,
    difficulty: "Easy",
    question:
      "Which traditional percussion instrument (small and handheld) is used in Venezuelan music?",
    category: charactersAndPopularCulture,
    correct_answer: "Maracas",
    incorrect_answers: ["Hawaiian lap steel", "Korean djembe", "Balalaika"],
  },
  {
    id: 69,
    difficulty: "Easy",
    question:
      "Which Venezuelan actor or actress has worked internationally in soap operas or movies (well-known figure)?",
    category: charactersAndPopularCulture,
    correct_answer: "Gaby Espino",
    incorrect_answers: ["Meryl Streep", "Kate Winslet", "Penélope Cruz"],
  },
  {
    id: 70,
    difficulty: "Easy",
    question:
      "Which colloquial expression is used in Venezuela to say 'friend' or 'buddy' (informal)?",
    category: charactersAndPopularCulture,
    correct_answer: "Pana",
    incorrect_answers: ["Mate", "Broccoli", "Chum"],
  },
  {
    id: 71,
    difficulty: "Easy",
    question:
      "What main ingredient does the soup called 'sancocho' in Venezuela have?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Meat and tubers",
    incorrect_answers: ["Chocolate", "Cold cereals", "Ice cream"],
  },
  {
    id: 72,
    difficulty: "Easy",
    question:
      "Which nut or seed is used in some Venezuelan recipes to decorate or add flavor (very common in desserts)?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Coconut",
    incorrect_answers: ["Pistachio", "Hazelnut", "Cashew nut"],
  },
  {
    id: 73,
    difficulty: "Easy",
    question:
      "What is a common breakfast in Venezuela that includes arepa and cheese?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Arepa with cheese",
    incorrect_answers: [
      "Porridge with blueberries",
      "Panini with pesto",
      "Breakfast sushi",
    ],
  },
  {
    id: 74,
    difficulty: "Easy",
    question:
      "Which Venezuelan street fast food is often sold at stalls and is fried dough filled with cheese or meat?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Empanada",
    incorrect_answers: ["French crepe", "Doner kebab", "Japanese hot dog"],
  },
  {
    id: 75,
    difficulty: "Easy",
    question:
      "Which cold dessert based on milk and eggs is very popular in Venezuela?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Quesillo",
    incorrect_answers: ["Italian gelato", "Turkish baklava", "Gulab jamun"],
  },
  {
    id: 76,
    difficulty: "Easy",
    question:
      "Which typical dish is made with black beans and is part of pabellón?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Black beans (caraotas negras)",
    incorrect_answers: ["Red lentils", "Hummus", "Chili con carne"],
  },
  {
    id: 77,
    difficulty: "Easy",
    question:
      "Which tropical fruit is widely used to make juices and smoothies in Venezuela, it is yellow and sweet?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Mango",
    incorrect_answers: ["Apple", "Pear", "Grape"],
  },
  {
    id: 78,
    difficulty: "Easy",
    question:
      "Which Venezuelan snack made from fried plantain is eaten salty and crispy?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Tostones / tajadas",
    incorrect_answers: [
      "French fries with tartar sauce",
      "Pretzels",
      "Onion rings",
    ],
  },
  {
    id: 79,
    difficulty: "Easy",
    question:
      "What is a popular filling for arepas that consists of shredded chicken with mayonnaise or sauce?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Shredded chicken",
    incorrect_answers: ["Smoked salmon", "Russian caviar", "Foie gras"],
  },
  {
    id: 80,
    difficulty: "Easy",
    question:
      "Which thick soup made with plantain and meat is typical in some regions of Venezuela?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Mazamorra or plantain-based soups",
    incorrect_answers: ["Ramen", "Minestrone", "Borscht"],
  },
  {
    id: 81,
    difficulty: "Easy",
    question:
      "What is the very commonly used informal greeting to say 'hello' in Venezuela?",
    category: charactersAndPopularCulture,
    correct_answer: "Hola / Buenas",
    incorrect_answers: ["Howdy", "Guten Tag", "Ciao bella"],
  },
  {
    id: 82,
    difficulty: "Easy",
    question:
      "What type of dance is performed at traditional Venezuelan festivities, especially in the plains?",
    category: charactersAndPopularCulture,
    correct_answer: "Joropo",
    incorrect_answers: ["Classical ballet", "Argentinian tango", "Flamenco"],
  },
  {
    id: 83,
    difficulty: "Easy",
    question:
      "Which typical Venezuelan instrument is similar to a small guitar and has four strings?",
    category: charactersAndPopularCulture,
    correct_answer: "Cuatro",
    incorrect_answers: ["Sitar", "Banjo", "Balalaika"],
  },
  {
    id: 84,
    difficulty: "Easy",
    question:
      "What sport has historically had many famous players originating from Venezuela?",
    category: charactersAndPopularCulture,
    correct_answer: "Baseball",
    incorrect_answers: ["Alpine skiing", "Ice hockey", "Lacrosse"],
  },
  {
    id: 85,
    difficulty: "Easy",
    question:
      "What Venezuelan word is used to mean 'job' in some informal contexts (e.g. 'chamba')?",
    category: charactersAndPopularCulture,
    correct_answer: "Chamba",
    incorrect_answers: ["Gig (in English)", "Shift (in English)", "Jobo"],
  },
  {
    id: 86,
    difficulty: "Easy",
    question:
      "What is a popular Venezuelan musical genre that also inspires festivities and dances?",
    category: charactersAndPopularCulture,
    correct_answer: "Joropo",
    incorrect_answers: ["Techno", "Hard rock", "Grunge"],
  },
  {
    id: 87,
    difficulty: "Easy",
    question:
      "Which Venezuelan actor or actress was Miss Universe or Miss World (well-known beauty queen)?",
    category: charactersAndPopularCulture,
    correct_answer:
      "Silhouette of famous winners (e.g., Venezuela has had several international queens to date)",
    incorrect_answers: ["Marilyn Monroe", "Audrey Hepburn", "Grace Kelly"],
  },
  {
    id: 88,
    difficulty: "Easy",
    question:
      "Which cold fruit-based drink is common at Venezuelan street stands?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Fresh fruit juice",
    incorrect_answers: ["Latte macchiato", "Matcha latte", "Fruit kefir"],
  },
  {
    id: 89,
    difficulty: "Easy",
    question:
      "Which typical product combining corn and cheese is eaten as a hot snack or at fairs?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Cachapa with cheese",
    incorrect_answers: [
      "Pancake with syrup",
      "Scones with cream",
      "Nutella crepe",
    ],
  },
  {
    id: 90,
    difficulty: "Easy",
    question:
      "Which Venezuelan coast is famous for its turquoise beaches and cays (national park)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Morrocoy (Morrocoy National Park, Falcón)",
    incorrect_answers: ["Cape Horn", "Faroe Islands", "Amalfi Coast"],
  },
  {
    id: 91,
    difficulty: "Easy",
    question:
      "What is the longest river in Venezuela (one of the most important)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Orinoco",
    incorrect_answers: ["Amazon", "Nile", "Mississippi"],
  },
  {
    id: 92,
    difficulty: "Easy",
    question:
      "What word in Venezuela is commonly used to refer to the beach informally (e.g. common 'playa')?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Playa",
    incorrect_answers: ["Shoreline", "Strand", "Rivage"],
  },
  {
    id: 93,
    difficulty: "Easy",
    question:
      "Which city is known as 'the land of Grace' and has a historic cathedral (Nueva Esparta state)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Cumaná (nicknamed 'Land of Grace')",
    incorrect_answers: ["Maracaibo", "Valencia", "Caracas"],
  },
  {
    id: 94,
    difficulty: "Easy",
    question:
      "Which Venezuelan national park protects the tepuis and unique landscapes (such as Roraima and Auyán-tepui)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Canaima National Park",
    incorrect_answers: [
      "Yellowstone National Park",
      "Banff National Park",
      "Kruger National Park",
    ],
  },
  {
    id: 95,
    difficulty: "Easy",
    question:
      "Which peaceful and touristic bay is located in Nueva Esparta state?",
    category: placesAndCitiesOfVenezuela,
    correct_answer:
      "The Bay of Puerto La Cruz / Nearby islands (e.g. Margarita)",
    incorrect_answers: ["Hudson Bay", "Biscayne Bay", "Bay of Fundy"],
  },
  {
    id: 96,
    difficulty: "Easy",
    question:
      "Which wind instrument is common in some traditional Venezuelan bands?",
    category: charactersAndPopularCulture,
    correct_answer: "Flute",
    incorrect_answers: ["Didgeridoo", "Bagpipes", "Theremin"],
  },
  {
    id: 97,
    difficulty: "Easy",
    question:
      "Which famous Venezuelan conductor studied in El Sistema and conducts international orchestras?",
    category: charactersAndPopularCulture,
    correct_answer: "Gustavo Dudamel",
    incorrect_answers: ["Andrea Bocelli", "Yo-Yo Ma", "John Williams"],
  },
  {
    id: 98,
    difficulty: "Easy",
    question:
      "What Venezuelan word is used to refer to 'money' colloquially (e.g. 'plata')?",
    category: charactersAndPopularCulture,
    correct_answer: "Plata",
    incorrect_answers: ["Beef", "Fruit", "Paper"],
  },
  {
    id: 99,
    difficulty: "Easy",
    question:
      "Which Venezuelan city is known for its tradition in the automotive industry and is in the center of the country?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Valencia",
    incorrect_answers: ["Porlamar", "Coro", "Tucupita"],
  },
  {
    id: 100,
    difficulty: "Easy",
    question:
      "Which traditional Venezuelan dessert is served in the form of flan and is very popular in celebrations?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Quesillo",
    incorrect_answers: ["Apple pie", "Chocolate brownie", "Pavlova"],
  },
];

// export const questions = [
//   {
//     id: 1,
//     difficulty: "Fácil",
//     question: "¿Qué evento inició la Primera Guerra Mundial?",
//     category: historia,
//     correct_answer: "El asesinato del Archiduque Franz Ferdinand de Austria",
//     incorrect_answers: [
//       "El hundimiento del Titanic",
//       "La invasión de Polonia por Alemania",
//       "La Revolución Francesa",
//     ],
//   },
//   {
//     id: 2,
//     difficulty: "Fácil",
//     question: '¿Quién es el autor de "Cien años de soledad"?        ',
//     category: literatura,
//     correct_answer: "Gabriel García Márquez",
//     incorrect_answers: ["Julio Cortázar", "Mario Vargas Llosa", "Pablo Neruda"],
//   },
//   {
//     id: 3,
//     difficulty: "Fácil",
//     question: "¿En qué deporte se utiliza un disco?",
//     category: deportes,
//     correct_answer: "Hockey sobre hielo",
//     incorrect_answers: ["Fútbol", "Baloncesto", "Béisbol"],
//   },
//   {
//     id: 4,
//     difficulty: "Medio",
//     question: "¿Qué sustancia es conocida como la 'molécula de la vida'?",
//     category: ciencia,
//     correct_answer: "El ADN",
//     incorrect_answers: ["La glucosa", "La insulina", "La proteína"],
//   },
//   {
//     id: 5,
//     difficulty: "Difícil",
//     question: "¿Quién es considerado el padre de la filosofía occidental?",
//     category: filosofia,
//     correct_answer: "Sócrates",
//     incorrect_answers: ["Aristóteles", "Platón", "Nietzsche"],
//   },
//   {
//     id: 6,
//     difficulty: "Medio",
//     question: "¿En qué año fue fundada la compañía Apple?",
//     category: tecnologia,
//     correct_answer: "1976",
//     incorrect_answers: ["1984", "1991", "1967"],
//   },
//   {
//     id: 7,
//     difficulty: "Fácil",
//     question: "¿Cuál es el río más largo del mundo?",
//     category: geografia,
//     correct_answer: "El Río Amazonas",
//     incorrect_answers: ["El Río Nilo", "El Río Yangtze", "El Río Misisipi"],
//   },
//   {
//     id: 8,
//     difficulty: "Medio",
//     question: "¿Cuál es el océano más grande del mundo?",
//     category: geografia,
//     correct_answer: "El Océano Pacífico",
//     incorrect_answers: [
//       "El Océano Atlántico",
//       "El Océano Índico",
//       "El Océano Ártico",
//     ],
//   },
//   {
//     id: 9,
//     difficulty: "Difícil",
//     question: "¿Cuál es la obra más famosa de William Shakespeare?",
//     category: literatura,
//     correct_answer: "Hamlet",
//     incorrect_answers: ["Romeo y Julieta", "Macbeth", "El Rey Lear"],
//   },
//   {
//     id: 10,
//     difficulty: "Medio",
//     question: "¿Qué es lo que se mide con la escala de Richter?",
//     category: ciencia,
//     correct_answer: "La magnitud de los terremotos",
//     incorrect_answers: [
//       "La velocidad del sonido",
//       "La intensidad de los huracanes",
//       "La temperatura en grados Fahrenheit",
//     ],
//   },
//   {
//     id: 11,
//     difficulty: "Fácil",
//     question: "¿Qué país ganó el primer Mundial de Fútbol?",
//     category: deportes,
//     correct_answer: "Uruguay",
//     incorrect_answers: ["Brasil", "Argentina", "Alemania"],
//   },
//   {
//     id: 12,
//     difficulty: "Medio",
//     question: "¿Qué es el efecto invernadero?",
//     category: ciencia,
//     correct_answer: "Un fenómeno atmosférico que retiene el calor en la Tierra",
//     incorrect_answers: [
//       "Un tipo de casa de vidrio para plantas",
//       "Un proceso químico para conservar alimentos",
//       "Un tipo de sistema de calefacción para edificios",
//     ],
//   },
//   {
//     id: 13,
//     difficulty: "Medio",
//     question:
//       "¿En qué año se celebraron los primeros Juegos Olímpicos modernos?",
//     category: deportes,
//     correct_answer: "1896",
//     incorrect_answers: ["1900", "1924", "1936"],
//   },
//   {
//     id: 14,
//     difficulty: "Fácil",
//     question: "¿Cuál es el planeta más grande del sistema solar?",
//     category: ciencia,
//     correct_answer: "Júpiter",
//     incorrect_answers: ["Saturno", "Neptuno", "Urano"],
//   },
//   {
//     id: 15,
//     difficulty: "Fácil",
//     question: "¿Quién escribió la obra 'Don Quijote de la Mancha'?",
//     category: literatura,
//     correct_answer: "Miguel de Cervantes",
//     incorrect_answers: [
//       "Federico García Lorca",
//       "Gabriel García Márquez",
//       "Pablo Neruda",
//     ],
//   },
//   {
//     id: 16,
//     difficulty: "Medio",
//     question: "¿Cuál es el elemento químico más abundante en la Tierra?",
//     category: ciencia,
//     correct_answer: "Oxígeno",
//     incorrect_answers: ["Nitrógeno", "Hierro", "Silicio"],
//   },
//   {
//     id: 17,
//     difficulty: "Medio",
//     question: "¿Cuál es el país más poblado del mundo?",
//     category: geografia,
//     correct_answer: "China",
//     incorrect_answers: ["India", "Estados Unidos", "Brasil"],
//   },
//   {
//     id: 18,
//     difficulty: "Medio",
//     question: "¿Quién es considerado el padre de la filosofía occidental?",
//     category: filosofia,
//     correct_answer: "Sócrates",
//     incorrect_answers: ["Platón", "Aristóteles", "Descartes"],
//   },
//   {
//     id: 19,
//     difficulty: "Difícil",
//     question: "¿Qué científico propuso la teoría del Big Bang?",
//     category: ciencia,
//     correct_answer: "Georges Lemaître",
//     incorrect_answers: ["Albert Einstein", "Stephen Hawking", "Isaac Newton"],
//   },
//   {
//     id: 20,
//     difficulty: "Fácil",
//     question: '¿Quién es el autor de la novela "El viejo y el mar"?',
//     category: literatura,
//     correct_answer: "Ernest Hemingway",
//     incorrect_answers: [
//       "William Shakespeare",
//       "J.K. Rowling",
//       "F. Scott Fitzgerald",
//     ],
//   },
//   {
//     id: 21,
//     difficulty: "Fácil",
//     question: "¿Cuál es el órgano más grande del cuerpo humano?",
//     category: ciencia,
//     correct_answer: "La piel",
//     incorrect_answers: ["El hígado", "El corazón", "Los pulmones"],
//   },
//   {
//     id: 22,
//     difficulty: "Medio",
//     question: "¿Quién es el creador del sistema operativo Linux?",
//     category: tecnologia,
//     correct_answer: "Linus Torvalds",
//     incorrect_answers: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg"],
//   },
//   {
//     id: 23,
//     difficulty: "Medio",
//     question: "¿En qué año terminó la Segunda Guerra Mundial?",
//     category: historia,
//     correct_answer: "1945",
//     incorrect_answers: ["1939", "1941", "1943"],
//   },
//   {
//     id: 24,
//     difficulty: "Fácil",
//     question: "¿Cuál es el planeta más cercano al Sol?",
//     category: ciencia,
//     correct_answer: "Mercurio",
//     incorrect_answers: ["Venus", "Marte", "Júpiter"],
//   },
//   {
//     id: 25,
//     difficulty: "Medio",
//     question:
//       "¿Qué escritor es conocido por haber escrito 'Cien años de soledad'?",
//     category: literatura,
//     correct_answer: "Gabriel García Márquez",
//     incorrect_answers: ["Jorge Luis Borges", "Pablo Neruda", "Julio Cortázar"],
//   },
//   {
//     id: 26,
//     difficulty: "Difícil",
//     question: "¿Qué país es el más grande en términos de superficie terrestre?",
//     category: geografia,
//     correct_answer: "Rusia",
//     incorrect_answers: ["Estados Unidos", "China", "Australia"],
//   },
//   {
//     id: 27,
//     difficulty: "Medio",
//     question: "¿Cuál es la capital de Canadá?",
//     category: geografia,
//     correct_answer: "Ottawa",
//     incorrect_answers: ["Toronto", "Montreal", "Vancouver"],
//   },
//   {
//     id: 28,
//     difficulty: "Fácil",
//     question: "¿Qué elemento químico tiene el símbolo H?",
//     category: ciencia,
//     correct_answer: "Hidrógeno",
//     incorrect_answers: ["Helio", "Hierro", "Hormigón"],
//   },
//   {
//     id: 29,
//     difficulty: "Medio",
//     question:
//       "¿Qué jugador de fútbol ha ganado más Balones de Oro en la historia?",
//     category: deportes,
//     correct_answer: "Lionel Messi",
//     incorrect_answers: ["Cristiano Ronaldo", "Johan Cruyff", "Diego Maradona"],
//   },
//   {
//     id: 30,
//     difficulty: "Fácil",
//     question: "¿En qué año ocurrió la Revolución Francesa?",
//     category: historia,
//     correct_answer: "1789",
//     incorrect_answers: ["1848", "1917", "1492"],
//   },
//   // -------------------
//   {
//     id: 31,
//     difficulty: "Fácil",
//     category: tecnologia,
//     question: "¿Qué significa la sigla HTML?",
//     correct_answer: "HyperText Markup Language",
//     incorrect_answers: [
//       "Hyperlinks and Text Markup Language",
//       "Home Tool Markup Language",
//       "Hyperlinking Text Markup Language",
//     ],
//   },
//   {
//     id: 32,
//     difficulty: "Fácil",
//     category: tecnologia,
//     question: "¿Cuál es el navegador web más utilizado en el mundo?",
//     correct_answer: "Google Chrome",
//     incorrect_answers: ["Safari", "Firefox", "Internet Explorer"],
//   },
//   {
//     id: 33,
//     difficulty: "Fácil",
//     category: tecnologia,
//     question:
//       "¿Qué lenguaje de programación es más utilizado para el desarrollo web?",
//     correct_answer: "JavaScript",
//     incorrect_answers: ["Python", "Java", "C++"],
//   },
//   {
//     id: 34,
//     difficulty: "Medio",
//     category: tecnologia,
//     question: "¿Qué es un servidor web?",
//     correct_answer: "Un programa que recibe y procesa solicitudes HTTP",
//     incorrect_answers: [
//       "Un programa que envía correos electrónicos",
//       "Un programa que protege la privacidad de los usuarios en línea",
//       "Un programa que realiza operaciones matemáticas complejas",
//     ],
//   },
//   {
//     id: 35,
//     difficulty: "Medio",
//     category: tecnologia,
//     question: "¿Qué es un ataque de phishing?",
//     correct_answer:
//       "Un intento de obtener información confidencial a través de un correo electrónico falso",
//     incorrect_answers: [
//       "Un virus que daña los archivos del ordenador",
//       "Un tipo de ataque DDoS",
//       "Un intento de secuestrar el tráfico de internet",
//     ],
//   },
//   {
//     id: 36,
//     difficulty: "Medio",
//     category: tecnologia,
//     question: "¿Qué es un archivo CSV?",
//     correct_answer: "Un archivo de texto con valores separados por comas",
//     incorrect_answers: [
//       "Un archivo de audio comprimido",
//       "Un archivo de imagen en formato vectorial",
//       "Un archivo de vídeo de alta definición",
//     ],
//   },
//   {
//     id: 37,
//     difficulty: "Difícil",
//     category: tecnologia,
//     question: "¿Qué es un algoritmo de cifrado asimétrico?",
//     correct_answer: "Un método de cifrado que utiliza dos claves diferentes",
//     incorrect_answers: [
//       "Un método de cifrado que utiliza la misma clave para cifrar y descifrar",
//       "Un método de cifrado que no utiliza claves",
//       "Un método de cifrado que solo se utiliza en aplicaciones militares",
//     ],
//   },
//   {
//     id: 38,
//     difficulty: "Difícil",
//     category: tecnologia,
//     question: "¿Qué es una red privada virtual (VPN)?",
//     correct_answer:
//       "Una conexión segura a una red privada a través de internet",
//     incorrect_answers: [
//       "Una red de computadoras en una organización",
//       "Una red de computadoras conectadas a internet",
//       "Una red de computadoras que solo utiliza tecnología inalámbrica",
//     ],
//   },
//   {
//     id: 39,
//     difficulty: "Difícil",
//     question: "¿En qué año se produjo la Guerra de los Cien Años?",
//     category: historia,
//     correct_answer: "1337",
//     incorrect_answers: ["1066", "1415", "1642"],
//   },
//   {
//     id: 40,
//     difficulty: "Fácil",
//     question: "¿En qué año se produjo el ataque a Pearl Harbor?",
//     category: historia,
//     correct_answer: "1941",
//     incorrect_answers: ["1939", "1942", "1945"],
//   },
//   {
//     id: 41,
//     difficulty: "Medio",
//     question: "¿Qué tratado dio fin a la Primera Guerra Mundial?",
//     category: historia,
//     correct_answer: "Tratado de Versalles",
//     incorrect_answers: [
//       "Tratado de Tordesillas",
//       "Tratado de Westfalia",
//       "Tratado de Nankín",
//     ],
//   },
//   {
//     id: 42,
//     difficulty: "Difícil",
//     question: "¿Quién fue el último emperador de la Dinastía Qing en China?",
//     category: historia,
//     correct_answer: "Puyi",
//     incorrect_answers: ["Hongwu", "Wuzong", "Kangxi"],
//   },
//   {
//     id: 43,
//     difficulty: "Fácil",
//     question:
//       "¿Cuál fue el nombre de la primera expedición de Cristóbal Colón?",
//     category: historia,
//     correct_answer: "La Santa María",
//     incorrect_answers: ["La Pinta", "La Niña", "La Santísima Trinidad"],
//   },
//   {
//     id: 44,
//     difficulty: "Medio",
//     question:
//       "¿Cuál fue el primer país en enviar un objeto hecho por el hombre a la luna?",
//     category: historia,
//     correct_answer: "Estados Unidos",
//     incorrect_answers: ["Unión Soviética", "China", "Japón"],
//   },
//   {
//     id: 45,
//     difficulty: "Difícil",
//     question:
//       "¿Cuál fue la primera ciudad en el mundo en tener una población de más de un millón de habitantes?",
//     category: historia,
//     correct_answer: "Roma",
//     incorrect_answers: ["Atenas", "Babilonia", "Nínive"],
//   },
//   {
//     id: 46,
//     difficulty: "Fácil",
//     question: "¿Quién fue el primer presidente de los Estados Unidos?",
//     category: historia,
//     correct_answer: "George Washington",
//     incorrect_answers: [
//       "Thomas Jefferson",
//       "Abraham Lincoln",
//       "Franklin D. Roosevelt",
//     ],
//   },
//   {
//     id: 47,
//     difficulty: "Medio",
//     question: "¿Cuál fue la primera dinastía en gobernar en China?",
//     category: historia,
//     correct_answer: "Xia",
//     incorrect_answers: ["Han", "Tang", "Song"],
//   },
//   {
//     id: 48,
//     difficulty: "Fácil",
//     question: '¿Quién escribió la obra "Don Quijote de la Mancha"?',
//     category: literatura,
//     correct_answer: "Miguel de Cervantes",
//     incorrect_answers: [
//       "Gabriel García Márquez",
//       "Jorge Luis Borges",
//       "Pablo Neruda",
//     ],
//   },
//   {
//     id: 49,
//     difficulty: "Medio",
//     question:
//       "¿Cuál de las siguientes novelas es escrita por Gabriel García Márquez?",
//     category: literatura,
//     correct_answer: "Cien años de soledad",
//     incorrect_answers: [
//       "Rayuela",
//       "La ciudad y los perros",
//       "La casa de los espíritus",
//     ],
//   },
//   {
//     id: 50,
//     difficulty: "Difícil",
//     question: '¿Quién escribió "La metamorfosis"?',
//     category: literatura,
//     correct_answer: "Franz Kafka",
//     incorrect_answers: ["Virginia Woolf", "James Joyce", "F. Scott Fitzgerald"],
//   },
//   {
//     id: 51,
//     difficulty: "Fácil",
//     question: '¿Quién escribió "El retrato de Dorian Gray"?',
//     category: literatura,
//     correct_answer: "Oscar Wilde",
//     incorrect_answers: ["Edgar Allan Poe", "Emily Bronte", "Charles Dickens"],
//   },
//   {
//     id: 52,
//     difficulty: "Medio",
//     question:
//       "¿Cuál de las siguientes obras no fue escrita por William Shakespeare?",
//     category: literatura,
//     correct_answer: "Moby Dick",
//     incorrect_answers: ["Hamlet", "Macbeth", "Otelo"],
//   },
//   {
//     id: 53,
//     difficulty: "Difícil",
//     question:
//       "¿Cuál de las siguientes obras de José Saramago recibió el Premio Nobel de Literatura?",
//     category: literatura,
//     correct_answer: "Ensayo sobre la ceguera",
//     incorrect_answers: [
//       "La caverna",
//       "El evangelio según Jesucristo",
//       "Las intermitencias de la muerte",
//     ],
//   },
//   {
//     id: 54,
//     difficulty: "Fácil",
//     question: '¿Quién escribió la novela "El guardián entre el centeno"?',
//     category: literatura,
//     correct_answer: "J.D. Salinger",
//     incorrect_answers: [
//       "F. Scott Fitzgerald",
//       "Ernest Hemingway",
//       "Tennessee Williams",
//     ],
//   },
//   {
//     id: 55,
//     difficulty: "Difícil",
//     question: "¿Cuál es el país más grande de África?",
//     category: geografia,
//     correct_answer: "Argelia",
//     incorrect_answers: ["Sudán", "Libia", "República Democrática del Congo"],
//   },
//   {
//     id: 56,
//     difficulty: "Fácil",
//     question: "¿Cuál es el país más grande del mundo?",
//     category: geografia,
//     correct_answer: "Rusia",
//     incorrect_answers: ["China", "Estados Unidos", "Canadá"],
//   },
//   {
//     id: 57,
//     difficulty: "Medio",
//     question: "¿En qué continente se encuentra el lago Baikal?",
//     category: geografia,
//     correct_answer: "Asia",
//     incorrect_answers: ["Europa", "África", "América del Sur"],
//   },
//   {
//     id: 58,
//     difficulty: "Medio",
//     question: "¿Cuál es el país más poblado del mundo?",
//     category: geografia,
//     correct_answer: "China",
//     incorrect_answers: ["India", "Estados Unidos", "Indonesia"],
//   },
//   {
//     id: 59,
//     difficulty: "Difícil",
//     question: "¿Cuál es la montaña más alta del mundo?",
//     category: geografia,
//     correct_answer: "El Monte Everest",
//     incorrect_answers: ["El K2", "El Mont Blanc", "El Aconcagua"],
//   },
//   {
//     id: 60,
//     difficulty: "Difícil",
//     question: "¿Cuál es el país más pequeño del mundo?",
//     category: geografia,
//     correct_answer: "El Vaticano",
//     incorrect_answers: ["Mónaco", "Nauru", "Tuvalu"],
//   },
//   {
//     id: 61,
//     difficulty: "Medio",
//     question: "¿Cuál es el país más extenso de África?",
//     category: geografia,
//     correct_answer: "Argelia",
//     incorrect_answers: ["Nigeria", "Egipto", "Sudáfrica"],
//   },
//   {
//     id: 62,
//     difficulty: "Fácil",
//     question: "¿Qué país ganó la Copa Mundial de la FIFA en 2018?",
//     category: deportes,
//     correct_answer: "Francia",
//     incorrect_answers: ["Alemania", "Brasil", "Argentina"],
//   },
//   {
//     id: 63,
//     difficulty: "Fácil",
//     question: "¿Qué deporte se juega en Wimbledon?",
//     category: deportes,
//     correct_answer: "Tenis",
//     incorrect_answers: ["Golf", "Fútbol", "Rugby"],
//   },
//   {
//     id: 64,
//     difficulty: "Medio",
//     question: "¿Cuántos puntos vale un touchdown en el fútbol americano?",
//     category: deportes,
//     correct_answer: "6",
//     incorrect_answers: ["4", "7", "5"],
//   },
//   {
//     id: 65,
//     difficulty: "Medio",
//     question:
//       "¿Cuál es el jugador de baloncesto con más anillos de campeonato en la NBA?",
//     category: deportes,
//     correct_answer: "Bill Russell",
//     incorrect_answers: [
//       "Michael Jordan",
//       "Kareem Abdul-Jabbar",
//       "LeBron James",
//     ],
//   },
//   {
//     id: 66,
//     difficulty: "Medio",
//     question: "¿Cuál es el país de origen del futbolista Lionel Messi?",
//     category: deportes,
//     correct_answer: "Argentina",
//     incorrect_answers: ["Brasil", "España", "Portugal"],
//   },
//   {
//     id: 67,
//     difficulty: "Difícil",
//     question: "¿En qué año se celebraron los Juegos Olímpicos de Beijing?",
//     category: deportes,
//     correct_answer: "2008",
//     incorrect_answers: ["2012", "2004", "2016"],
//   },
//   {
//     id: 68,
//     difficulty: "Difícil",
//     question:
//       "¿Quién es el máximo goleador en la historia de la Liga Española?",
//     category: deportes,
//     correct_answer: "Lionel Messi",
//     incorrect_answers: ["Cristiano Ronaldo", "Telmo Zarra", "Hugo Sánchez"],
//   },
//   {
//     id: 69,
//     difficulty: "Difícil",
//     question: '¿En qué deporte se utiliza el término "smash"?',
//     category: deportes,
//     correct_answer: "Bádminton",
//     incorrect_answers: ["Voleibol", "Tenis", "Squash"],
//   },
//   {
//     id: 70,
//     category: filosofia,
//     difficulty: "Fácil",
//     question: "¿Cuál es la obra más conocida de Platón?",
//     correct_answer: "La República",
//     incorrect_answers: ["El Banquete", "Timeo", "Fedón"],
//   },
//   {
//     id: 71,
//     category: filosofia,
//     difficulty: "Medio",
//     question: "¿Cuál es el concepto central de la filosofía de Descartes?",
//     correct_answer: "El cogito ergo sum",
//     incorrect_answers: ["El empirismo", "El materialismo", "La fenomenología"],
//   },
//   {
//     id: 72,
//     category: filosofia,
//     difficulty: "Difícil",
//     question: "¿Qué es la dialéctica en la filosofía de Hegel?",
//     correct_answer:
//       "El método para llegar a la verdad mediante la contradicción",
//     incorrect_answers: [
//       "La creación de un sistema filosófico",
//       "La negación de la realidad",
//       "El análisis de los procesos cognitivos",
//     ],
//   },
//   {
//     id: 73,
//     category: filosofia,
//     difficulty: "Medio",
//     question: "¿Qué es el nihilismo en la filosofía?",
//     correct_answer: "La negación de todos los valores y creencias",
//     incorrect_answers: [
//       "La afirmación de la existencia de un ser superior",
//       "La creencia en la reencarnación",
//       "La negación de la existencia del mundo externo",
//     ],
//   },
//   {
//     id: 74,
//     category: filosofia,
//     difficulty: "Difícil",
//     question: "¿Qué es la deconstrucción en la filosofía de Jacques Derrida?",
//     correct_answer:
//       "El análisis crítico de la relación entre los significados y los conceptos",
//     incorrect_answers: [
//       "La creación de nuevos conceptos a partir de la combinación de los antiguos",
//       "La búsqueda de la verdad absoluta",
//       "La negación de la existencia del lenguaje",
//     ],
//   },
//   {
//     id: 75,
//     category: filosofia,
//     difficulty: "Fácil",
//     question: "¿Qué es la ética?",
//     correct_answer:
//       "La rama de la filosofía que estudia la moral y la conducta humana",
//     incorrect_answers: [
//       "La rama de la filosofía que estudia la lógica",
//       "La rama de la filosofía que estudia la mente",
//       "La rama de la filosofía que estudia el conocimiento",
//     ],
//   },
//   {
//     id: 76,
//     category: filosofia,
//     difficulty: "Medio",
//     question: "¿Qué es el imperativo categórico en la filosofía de Kant?",
//     correct_answer: "La regla moral que se debe seguir en cualquier situación",
//     incorrect_answers: [
//       "La creencia en la existencia de un Dios creador",
//       "La negación de la libertad humana",
//       "La afirmación de la existencia de una verdad absoluta",
//     ],
//   },
//   {
//     id: 77,
//     difficulty: "Fácil",
//     question: '¿Quién fue el autor de la obra "La República"?',
//     category: filosofia,
//     correct_answer: "Platón",
//     incorrect_answers: ["Aristóteles", "Sócrates", "Nietzsche"],
//   },
//   {
//     id: 78,
//     difficulty: "Medio",
//     question:
//       "¿Cuál es el término filosófico para referirse al estudio del conocimiento?",
//     category: filosofia,
//     correct_answer: "Epistemología",
//     incorrect_answers: ["Ontología", "Metafísica", "Lógica"],
//   },
//   {
//     id: 79,
//     difficulty: "Difícil",
//     question:
//       '¿Quién escribió el libro "El mundo como voluntad y representación"?',
//     category: filosofia,
//     correct_answer: "Arthur Schopenhauer",
//     incorrect_answers: [
//       "Friedrich Nietzsche",
//       "Immanuel Kant",
//       "Jean-Paul Sartre",
//     ],
//   },
//   {
//     id: 80,
//     difficulty: "Difícil",
//     question: "¿Cuál es la partícula subatómica más pesada?",
//     category: ciencia,
//     correct_answer: "Quark top",
//     incorrect_answers: ["Electrón", "Protón", "Neutrón"],
//   },
//   {
//     id: 81,
//     category: ciencia,
//     difficulty: "Medio",
//     question: "¿Qué es la capa de ozono?",
//     correct_answer:
//       "Una capa de gas que protege la Tierra de la radiación ultravioleta del sol",
//     incorrect_answers: [
//       "Una capa de nubes en la atmósfera",
//       "La capa más externa de la Tierra",
//       "Una capa de gases que produce el efecto invernadero",
//     ],
//   },
//   {
//     id: 82,
//     category: ciencia,
//     difficulty: "Difícil",
//     question: "¿Qué es la antimateria?",
//     correct_answer:
//       "Una forma de materia que tiene propiedades opuestas a la materia ordinaria",
//     incorrect_answers: [
//       "Una forma de materia que no tiene carga eléctrica",
//       "Una forma de materia que no tiene masa",
//       "Una forma de energía que tiene la capacidad de desintegrar la materia",
//     ],
//   },
//   {
//     id: 83,
//     difficulty: "Fácil",
//     question: '¿Qué es el acrónimo "CPU" en inglés?',
//     category: tecnologia,
//     correct_answer: "Central Processing Unit",
//     incorrect_answers: [
//       "Computer Personal Unit",
//       "Central Personal Unit",
//       "Computer Processing Unit",
//     ],
//   },
//   {
//     id: 84,
//     difficulty: "Medio",
//     question:
//       "¿Cuál es el nombre de la primera computadora electrónica digital?",
//     category: tecnologia,
//     correct_answer: "ENIAC",
//     incorrect_answers: ["UNIVAC", "COLOSSUS", "EDSAC"],
//   },
// ];
