import Ciencia from "./assets/ciencia.png";
import Deportes from "./assets/deportes.png";
import Filosofia from "./assets/filosofía.png";
import Geografia from "./assets/geografía.png";
import Historia from "./assets/historia.png";
import Literatura from "./assets/literatura.png";
import Tecnologia from "./assets/tecnología.png";
import SymbolsOfVenezuela from "./assets/symbolsofvenezuela.png";
import VenezuelanFoodsAndFlavors from "./assets/venezuelanfoodsandflavors.png";
import PlacesAndCitiesOfVenezuela from "./assets/placesandcitiesofvenezuela.png";
import CharactersAndPopularCulture from "./assets/charactersandpopularculture.png";

export const imgs = [
  Ciencia,
  Deportes,
  Filosofia,
  Geografia,
  Historia,
  Literatura,
  Tecnologia,
  SymbolsOfVenezuela,
  VenezuelanFoodsAndFlavors,
  PlacesAndCitiesOfVenezuela,
  CharactersAndPopularCulture,
];

export const categories = {
  historia: "Historia",
  literatura: "Literatura",
  deportes: "Deportes",
  ciencia: "Ciencia",
  filosofia: "Filosofía",
  tecnologia: "Tecnología",
  geografia: "Geografía",
  symbolsOfVenezuela: "Symbols of Venezuela",
  venezuelanFoodsAndFlavors: "Venezuelan Foods and Flavors",
  placesAndCitiesOfVenezuela: "Places and Cities of Venezuela",
  charactersAndPopularCulture: "Characters and Popular Culture",
};

const {
  historia,
  tecnologia,
  literatura,
  deportes,
  ciencia,
  filosofia,
  geografia,
  symbolsOfVenezuela,
  venezuelanFoodsAndFlavors,
  placesAndCitiesOfVenezuela,
  charactersAndPopularCulture,
} = categories;

export const categoryImages = {
  // usa las cadenas visibles (los valores de categories) como keys,
  // así puedes buscarlas directamente con el param `category`
  [categories.historia]: Historia, // si tienes la import Historia arriba
  [categories.literatura]: Literatura,
  [categories.deportes]: Deportes,
  [categories.ciencia]: Ciencia,
  [categories.filosofia]: Filosofia,
  [categories.tecnologia]: Tecnologia,
  [categories.geografia]: Geografia,
  [categories.symbolsOfVenezuela]: SymbolsOfVenezuela,
  [categories.venezuelanFoodsAndFlavors]: VenezuelanFoodsAndFlavors,
  [categories.placesAndCitiesOfVenezuela]: PlacesAndCitiesOfVenezuela,
  [categories.charactersAndPopularCulture]: CharactersAndPopularCulture,
};

export const questions = [
  {
    id: 1,
    difficulty: "Fácil",
    question: "¿De qué colores es la bandera de Venezuela?",
    category: symbolsOfVenezuela,
    correct_answer: "Amarillo, azul y rojo",
    incorrect_answers: [
      "Verde, blanco y rojo",
      "Azul, blanco y rojo",
      "Negro, amarillo y rojo",
    ],
  },
  {
    id: 2,
    difficulty: "Fácil",
    question: "¿Cuál es el himno nacional de Venezuela un símbolo nacional?",
    category: symbolsOfVenezuela,
    correct_answer: "El Himno Nacional",
    incorrect_answers: ["La Marcha Real", "La Marsellesa", "God Save the King"],
  },
  {
    id: 3,
    difficulty: "Fácil",
    question: "¿Cuál es el ave nacional de Venezuela?",
    category: symbolsOfVenezuela,
    correct_answer: "Turpial",
    incorrect_answers: ["Quetzal", "Cóndor", "Guanábana"],
  },
  {
    id: 4,
    difficulty: "Fácil",
    question: "¿Cuál es el árbol nacional de Venezuela?",
    category: symbolsOfVenezuela,
    correct_answer: "Araguaney",
    incorrect_answers: ["Ceiba", "Quebracho", "Palo santo"],
  },
  {
    id: 5,
    difficulty: "Fácil",
    question: "¿Cuál es la flor nacional de Venezuela (Cattleya mossiae)?",
    category: symbolsOfVenezuela,
    correct_answer: "Orquídea",
    incorrect_answers: ["Rosa", "Girasol", "Lirio"],
  },
  {
    id: 6,
    difficulty: "Fácil",
    question: "¿Cuál es la moneda oficial de Venezuela?",
    category: symbolsOfVenezuela,
    correct_answer: "Bolívar",
    incorrect_answers: ["Peso", "Dólar canadiense", "Real"],
  },
  {
    id: 7,
    difficulty: "Fácil",
    question:
      "¿Qué famoso salto de agua de Venezuela es el más alto del mundo?",
    category: symbolsOfVenezuela,
    correct_answer: "Salto Ángel",
    incorrect_answers: [
      "Cataratas del Niágara",
      "Iguazú",
      "Cataratas Victoria",
    ],
  },
  {
    id: 8,
    difficulty: "Fácil",
    question:
      "¿Cuántas estrellas hay en la bandera venezolana (versión actual comúnmente vista)?",
    category: symbolsOfVenezuela,
    correct_answer: "8",
    incorrect_answers: ["7", "9", "6"],
  },
  {
    id: 9,
    difficulty: "Fácil",
    question: "¿Qué aparece en el centro del escudo de Venezuela?",
    category: symbolsOfVenezuela,
    correct_answer: "Un caballo y elementos agrícolas",
    incorrect_answers: [
      "Una torre y un león",
      "Una paloma con una rama",
      "Un faro y un ancla",
    ],
  },
  {
    id: 10,
    difficulty: "Fácil",
    question: "¿Cuál es una fecha patria importante en Venezuela?",
    category: symbolsOfVenezuela,
    correct_answer: "5 de julio (Declaración de Independencia)",
    incorrect_answers: ["4 de julio", "1 de mayo", "12 de octubre"],
  },
  {
    id: 11,
    difficulty: "Fácil",
    question: "¿Qué es una arepa?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Una torta plana de masa de maíz",
    incorrect_answers: [
      "Una sopa de pescado",
      "Un dulce de leche",
      "Una empanada de carne",
    ],
  },
  {
    id: 12,
    difficulty: "Fácil",
    question:
      "¿Cuál es el plato tradicional que combina carne mechada, arroz, caraotas y plátano?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Pabellón criollo",
    incorrect_answers: ["Sancocho", "Feijoada", "Paella"],
  },
  {
    id: 13,
    difficulty: "Fácil",
    question: "¿Qué dulce típico venezolano se hace con papelón y limón?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Papelón con limón",
    incorrect_answers: ["Mazapán", "Tres leches", "Churros"],
  },
  {
    id: 14,
    difficulty: "Fácil",
    question: "¿Qué son los tequeños?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Palitos de queso envueltos en masa frita",
    incorrect_answers: [
      "Un tipo de arepa dulce",
      "Galletas saladas",
      "Un postre de coco",
    ],
  },
  {
    id: 15,
    difficulty: "Fácil",
    question:
      "¿Qué comida venezolana se prepara tradicionalmente en diciembre y es típica en Navidad?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Hallaca",
    incorrect_answers: ["Tamales mexicanos", "Sushi", "Poutine"],
  },
  {
    id: 16,
    difficulty: "Fácil",
    question:
      "¿Cómo se llama la arepa dulce de maíz tierno que se come a menudo en Venezuela?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Cachapa",
    incorrect_answers: ["Arequipe", "Buñuelo", "Empanada de yuca"],
  },
  {
    id: 17,
    difficulty: "Fácil",
    question:
      "¿Qué bebida fermentada y fría a base de maíz es popular en Venezuela?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Chicha",
    incorrect_answers: ["Kéfir", "Sake", "Kombucha"],
  },
  {
    id: 18,
    difficulty: "Fácil",
    question: "¿Qué postre venezolano se hace con papaya verde y panela?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Dulce de lechosa",
    incorrect_answers: ["Quesillo", "Tres leches", "Bienmesabe"],
  },
  {
    id: 19,
    difficulty: "Fácil",
    question: "¿Cuál es un relleno muy común para las arepas en Venezuela?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Carne mechada",
    incorrect_answers: [
      "Sashimi de salmón",
      "Pasta al pesto",
      "Croquetas de alga",
    ],
  },
  {
    id: 20,
    difficulty: "Fácil",
    question:
      "¿Qué comida típica venezolana es una empanada de maíz frita muy popular en la calle?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Empanada venezolana",
    incorrect_answers: ["Samosa", "Crepe francés", "Dumpling"],
  },
  {
    id: 21,
    difficulty: "Fácil",
    question: "¿Cuál es la capital de Venezuela?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Caracas",
    incorrect_answers: ["Maracaibo", "Valencia", "Mérida"],
  },
  {
    id: 22,
    difficulty: "Fácil",
    question: "¿Qué ciudad venezolana está ubicada junto al Lago de Maracaibo?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Maracaibo",
    incorrect_answers: ["Puerto Ordaz", "Porlamar", "Maturín"],
  },
  {
    id: 23,
    difficulty: "Fácil",
    question:
      "¿En qué estado está ubicada la ciudad de Mérida, famosa por sus montañas?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Mérida",
    incorrect_answers: ["Zulia", "Anzoátegui", "Delta Amacuro"],
  },
  {
    id: 24,
    difficulty: "Fácil",
    question:
      "¿Cuál es la isla venezolana famosa por sus playas y llamada también 'Isla de Margarita'?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Margarita",
    incorrect_answers: ["Coche", "Bonaire", "Curazao"],
  },
  {
    id: 25,
    difficulty: "Fácil",
    question:
      "¿Qué región venezolana es conocida por el Salto Ángel y la Gran Sabana?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Guayana (estado Bolívar)",
    incorrect_answers: ["Los Llanos", "Andes", "Costa Oriental del Lago"],
  },
  {
    id: 26,
    difficulty: "Fácil",
    question:
      "¿Qué puerto importante se encuentra en el estado Anzoátegui, conocido por su actividad marítima?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Puerto La Cruz",
    incorrect_answers: ["La Guaira", "Puerto Cabello", "Punta Cardón"],
  },
  {
    id: 27,
    difficulty: "Fácil",
    question: "¿Cuál es la capital del estado Zulia?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Maracaibo",
    incorrect_answers: ["Cabimas", "San Cristóbal", "Barquisimeto"],
  },
  {
    id: 28,
    difficulty: "Fácil",
    question:
      "¿Qué ciudad venezolana es conocida por su importante industria y está en el centro del país (estado Carabobo)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Valencia",
    incorrect_answers: ["Ciudad Bolívar", "Puerto Ordaz", "Cumana"],
  },
  {
    id: 29,
    difficulty: "Fácil",
    question: "¿Cuál es la ciudad capital del estado Lara?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Barquisimeto",
    incorrect_answers: ["Valera", "Porlamar", "San Juan de los Morros"],
  },
  {
    id: 30,
    difficulty: "Fácil",
    question:
      "¿Qué ciudad es famosa por el teleférico y las montañas andinas (estado Mérida)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Mérida",
    incorrect_answers: ["La Guaira", "Maracay", "Coro"],
  },
  {
    id: 31,
    difficulty: "Fácil",
    question:
      "¿Qué equipo de béisbol profesional de Caracas es muy conocido en Venezuela?",
    category: charactersAndPopularCulture,
    correct_answer: "Leones del Caracas",
    incorrect_answers: [
      "Tiburones de La Guaira",
      "Magallanes",
      "Bravos de Margarita",
    ],
  },
  {
    id: 32,
    difficulty: "Fácil",
    question:
      "¿Quién es un cantante venezolano conocido por la salsa y el tema 'Llorarás'?",
    category: charactersAndPopularCulture,
    correct_answer: "Oscar D'León",
    incorrect_answers: ["Ricky Martin", "Marc Anthony", "Carlos Vives"],
  },
  {
    id: 33,
    difficulty: "Fácil",
    question:
      "¿Qué pianista y compositor venezolano es famoso por música tradicional y sericultura de canciones folclóricas (ej. 'Caballo Viejo')?",
    category: charactersAndPopularCulture,
    correct_answer: "Simón Díaz",
    incorrect_answers: ["Juanes", "Shakira", "Plácido Domingo"],
  },
  {
    id: 34,
    difficulty: "Fácil",
    question:
      "¿Qué atleta venezolana ganó medallas en salto triple (famosa en eventos internacionales)?",
    category: charactersAndPopularCulture,
    correct_answer: "Yulimar Rojas",
    incorrect_answers: ["María Sharapova", "Usain Bolt", "Carl Lewis"],
  },
  {
    id: 35,
    difficulty: "Fácil",
    question:
      "¿Qué director de orquesta venezolano es internacionalmente reconocido (exdirector de la Filarmónica de Los Ángeles)?",
    category: charactersAndPopularCulture,
    correct_answer: "Gustavo Dudamel",
    incorrect_answers: [
      "Zubin Mehta",
      "Herbert von Karajan",
      "Leonard Bernstein",
    ],
  },
  {
    id: 36,
    difficulty: "Fácil",
    question:
      "¿Qué programa humorístico venezolano fue muy popular durante décadas y mostraba sketches cómicos?",
    category: charactersAndPopularCulture,
    correct_answer: "Radio Rochela",
    incorrect_answers: [
      "Saturday Night Live",
      "Monty Python",
      "El Chavo del 8",
    ],
  },
  {
    id: 37,
    difficulty: "Fácil",
    question:
      "¿Cómo se llama el baile tradicional venezolano del llanero que usa arpa, cuatro y maracas?",
    category: charactersAndPopularCulture,
    correct_answer: "Joropo",
    incorrect_answers: ["Tango", "Samba", "Reguetón"],
  },
  {
    id: 38,
    difficulty: "Fácil",
    question:
      "¿Cuál de estos es un plato que ha inspirado música folclórica venezolana?",
    category: charactersAndPopularCulture,
    correct_answer: "Pabellón criollo",
    incorrect_answers: ["Sushi", "Pizza", "Curry"],
  },
  {
    id: 39,
    difficulty: "Fácil",
    question:
      "¿Qué instrumento musical de cuatro cuerdas es típico en la música venezolana?",
    category: charactersAndPopularCulture,
    correct_answer: "Cuatro",
    incorrect_answers: ["Guitarra eléctrica", "Violin", "Sitar"],
  },
  {
    id: 40,
    difficulty: "Fácil",
    question:
      "¿Qué feria o fiesta popular se celebra en muchas ciudades de Venezuela con música y comparsas (ejemplo: en Carnaval)?",
    category: charactersAndPopularCulture,
    correct_answer: "Carnaval",
    incorrect_answers: ["Oktoberfest", "Thanksgiving", "Diwali"],
  },
  {
    id: 41,
    difficulty: "Fácil",
    question:
      "¿Qué fruta es muy típica en Venezuela y se usa para hacer jugos y postres (amarilla, dulce)?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Mango",
    incorrect_answers: ["Manzana", "Arándano", "Frambuesa"],
  },
  {
    id: 42,
    difficulty: "Fácil",
    question:
      "¿Cómo se llama la sopa de carne y verduras típica de Venezuela que se cocina a menudo los fines de semana?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Sancocho",
    incorrect_answers: ["Miso", "Gazpacho", "Borscht"],
  },
  {
    id: 43,
    difficulty: "Fácil",
    question:
      "¿Qué tipo de queso suave y fresco se utiliza mucho en acompañamiento de arepas y cachapas?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Queso blanco fresco",
    incorrect_answers: ["Gorgonzola", "Cheddar añejo", "Roquefort"],
  },
  {
    id: 44,
    difficulty: "Fácil",
    question: "¿Qué cereal se usa para hacer arepas y empanadas venezolanas?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Harina de maíz precocida",
    incorrect_answers: [
      "Harina de trigo",
      "Harina de arroz",
      "Harina de avena",
    ],
  },
  {
    id: 45,
    difficulty: "Fácil",
    question:
      "¿Cuál es una bebida caliente tradicional en las mañanas venezolanas hecha con cacao o chocolate?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Chocolate caliente",
    incorrect_answers: ["Té matcha", "Café turco", "Kopi luwak"],
  },
  {
    id: 46,
    difficulty: "Fácil",
    question: "¿Qué bebida refrescante se prepara con papelón rallado y limón?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Agua de papelón con limón",
    incorrect_answers: [
      "Limonada con leche",
      "Té helado de durazno",
      "Gaseosa de tamarindo",
    ],
  },
  {
    id: 47,
    difficulty: "Fácil",
    question:
      "¿Qué marisco es popular en la costa venezolana y en arepas o empanadas de mariscos?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Camarón",
    incorrect_answers: ["Cangrejo gigante", "Anguila", "Trucha de agua dulce"],
  },
  {
    id: 48,
    difficulty: "Fácil",
    question:
      "¿Qué tipo de pan redondo y aplanado se usa en Venezuela como base para muchos rellenos?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Arepa",
    incorrect_answers: ["Baguette", "Ciabatta", "Naan"],
  },
  {
    id: 49,
    difficulty: "Fácil",
    question:
      "¿Qué fruta tropical se utiliza para preparar el popular postre 'dulce de lechosa'?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Papaya verde",
    incorrect_answers: ["Banana", "Manzana", "Cereza"],
  },
  {
    id: 50,
    difficulty: "Fácil",
    question:
      "¿Qué producto lácteo dulce y cremoso es muy consumido en Venezuela como postre (parecido al flan)?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Quesillo",
    incorrect_answers: ["Panna cotta", "Baklava", "Tiramisu"],
  },
  {
    id: 51,
    difficulty: "Fácil",
    question:
      "¿Cuál es la capital administrativa del estado Miranda y ciudad cercana a Caracas?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Los Teques",
    incorrect_answers: ["La Victoria", "Ciudad Bolívar", "Punto Fijo"],
  },
  {
    id: 52,
    difficulty: "Fácil",
    question:
      "¿Qué península venezolana es conocida por sus playas y por el Parque Nacional Morrocoy?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Peninsula de Paraguana",
    incorrect_answers: [
      "Península de Yucatán",
      "Península Ibérica",
      "Península de Kola",
    ],
  },
  {
    id: 53,
    difficulty: "Fácil",
    question:
      "¿Qué importante puerto venezolano está al norte de Caracas y sirve a la capital (estado Vargas/La Guaira)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "La Guaira",
    incorrect_answers: ["Puerto Madryn", "Puerto Montt", "Puerto Varas"],
  },
  {
    id: 54,
    difficulty: "Fácil",
    question:
      "¿En qué estado se encuentra la península de Paraguaná (conocida por playas y refinerías)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Falcón",
    incorrect_answers: ["Nueva Esparta", "Monagas", "Amazonas"],
  },
  {
    id: 55,
    difficulty: "Fácil",
    question:
      "¿Qué ciudad portuaria está al oeste del país y es sede de la industria petrolera (estado Zulia)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Maracaibo",
    incorrect_answers: ["Maturín", "Barcelona", "Valera"],
  },
  {
    id: 56,
    difficulty: "Fácil",
    question:
      "¿Qué estado venezolano es conocido por sus llanuras y ganadería, famoso en la música llanera?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Lara/Los Llanos (ejemplo: estado Guárico o Apure)",
    incorrect_answers: ["Mérida andina", "Sucre insular", "Zulia montañoso"],
  },
  {
    id: 57,
    difficulty: "Fácil",
    question:
      "¿Qué ciudad es conocida por su historia colonial y su centro colonial bien conservado (estado Falcón)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Coro",
    incorrect_answers: ["Puerto Ordaz", "Maracay", "San Felipe"],
  },
  {
    id: 58,
    difficulty: "Fácil",
    question:
      "¿Qué ciudad turística en el oriente de Venezuela es famosa por playas y vida nocturna (estado Nueva Esparta)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Porlamar (Isla de Margarita)",
    incorrect_answers: ["Cumaná", "Maturín", "San Cristóbal"],
  },
  {
    id: 59,
    difficulty: "Fácil",
    question:
      "¿Qué ciudad se ubica en la confluencia de los ríos Orinoco y Caroní y es parte de la zona industrial Guayana?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Ciudad Guayana / Puerto Ordaz",
    incorrect_answers: ["Maracay", "Valencia", "Los Teques"],
  },
  {
    id: 60,
    difficulty: "Fácil",
    question:
      "¿Qué región de Venezuela es famosa por su paisaje de tepuyes y mesetas (como el Auyán-tepui)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "La Gran Sabana (Guayana)",
    incorrect_answers: [
      "Los Llanos",
      "Cordillera de los Andes",
      "Costa Oriental",
    ],
  },
  {
    id: 61,
    difficulty: "Fácil",
    question:
      "¿Qué famoso pelotero venezolano juega en las Grandes Ligas y es conocido por su estatura baja pero gran habilidad (jugador popular)?",
    category: charactersAndPopularCulture,
    correct_answer: "José Altuve",
    incorrect_answers: ["Cristiano Ronaldo", "LeBron James", "Lionel Messi"],
  },
  {
    id: 62,
    difficulty: "Fácil",
    question:
      "¿Qué cantante nacido en Venezuela es conocido por baladas y éxitos internacionales (familia Montaner)?",
    category: charactersAndPopularCulture,
    correct_answer: "Ricardo Montaner",
    incorrect_answers: ["Shakira", "Enrique Iglesias", "Luis Fonsi"],
  },
  {
    id: 63,
    difficulty: "Fácil",
    question:
      "¿Qué presentador o figura de la televisión venezolana es famoso por programas infantiles clásicos (ejemplo histórico)?",
    category: charactersAndPopularCulture,
    correct_answer: "Renny Ottolina (figura histórica de TV)",
    incorrect_answers: ["Bill Cosby", "David Letterman", "Conan O'Brien"],
  },
  {
    id: 64,
    difficulty: "Fácil",
    question:
      "¿Qué deporte es considerado el más popular en Venezuela junto al béisbol?",
    category: charactersAndPopularCulture,
    correct_answer: "Fútbol",
    incorrect_answers: ["Hockey sobre hielo", "Curling", "Cricket"],
  },
  {
    id: 65,
    difficulty: "Fácil",
    question:
      "¿Cómo se llama el famoso género musical venezolano que usa arpa, cuatro y maracas?",
    category: charactersAndPopularCulture,
    correct_answer: "Joropo",
    incorrect_answers: ["Reggae", "Reguetón", "K-pop"],
  },
  {
    id: 66,
    difficulty: "Fácil",
    question: "¿Qué figura literaria venezolana escribió 'Doña Bárbara'?",
    category: charactersAndPopularCulture,
    correct_answer: "Rómulo Gallegos",
    incorrect_answers: [
      "Gabriel García Márquez",
      "Pablo Neruda",
      "Isabel Allende",
    ],
  },
  {
    id: 67,
    difficulty: "Fácil",
    question:
      "¿Qué festival de música o baile es típico en muchas regiones de Venezuela durante las fiestas patronales?",
    category: charactersAndPopularCulture,
    correct_answer: "Comparsas y parrandas",
    incorrect_answers: ["La Tomatina", "Oktoberfest", "Diwali"],
  },
  {
    id: 68,
    difficulty: "Fácil",
    question:
      "¿Qué tradicional instrumento de percusión se usa en la música venezolana (pequeño y de mano)?",
    category: charactersAndPopularCulture,
    correct_answer: "Maracas",
    incorrect_answers: ["Tablas hawaianas", "Djembe coreano", "Balalaika"],
  },
  {
    id: 69,
    difficulty: "Fácil",
    question:
      "¿Qué actor o actriz venezolana ha trabajado internacionalmente en telenovelas o cine (figura conocida)?",
    category: charactersAndPopularCulture,
    correct_answer: "Gaby Espino",
    incorrect_answers: ["Meryl Streep", "Kate Winslet", "Penélope Cruz"],
  },
  {
    id: 70,
    difficulty: "Fácil",
    question:
      "¿Qué expresión coloquial se usa en Venezuela para decir 'amigo' o 'compañero' (informal)?",
    category: charactersAndPopularCulture,
    correct_answer: "Pana",
    incorrect_answers: ["Mate", "Broccoli", "Chum"],
  },
  {
    id: 71,
    difficulty: "Fácil",
    question:
      "¿Qué ingrediente principal lleva la sopa llamada 'sancocho' en Venezuela?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Carne y tubérculos",
    incorrect_answers: ["Chocolate", "Cereales fríos", "Helado"],
  },
  {
    id: 72,
    difficulty: "Fácil",
    question:
      "¿Qué fruto seco o semilla se utiliza en algunas recetas venezolanas para decorar o dar sabor (muy común en postres)?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Coco",
    incorrect_answers: ["Pistacho", "Avellana", "Castaña de cajú"],
  },
  {
    id: 73,
    difficulty: "Fácil",
    question:
      "¿Cuál es un desayuno común en Venezuela que incluye arepa y queso?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Arepa con queso",
    incorrect_answers: [
      "Porridge con arándanos",
      "Panini con pesto",
      "Sushi de desayuno",
    ],
  },
  {
    id: 74,
    difficulty: "Fácil",
    question:
      "¿Qué comida rápida callejera venezolana suele venderse en puestos y es una masa frita rellena de queso o carne?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Empanada",
    incorrect_answers: ["Creppe francés", "Doner kebab", "Hot dog japonés"],
  },
  {
    id: 75,
    difficulty: "Fácil",
    question:
      "¿Qué postre frío a base de leche y huevos es muy popular en Venezuela?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Quesillo",
    incorrect_answers: ["Gelato italiano", "Baklava turco", "Gulab jamun"],
  },
  {
    id: 76,
    difficulty: "Fácil",
    question:
      "¿Qué plato típico se hace con caraotas (frijoles) negras y es parte del pabellón?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Caraotas negras",
    incorrect_answers: ["Lentejas rojas", "Hummus", "Chili con carne"],
  },
  {
    id: 77,
    difficulty: "Fácil",
    question:
      "¿Qué fruta tropical se usa mucho para hacer jugos y batidos en Venezuela, es amarillo y dulce?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Mango",
    incorrect_answers: ["Manzana", "Pera", "Uva"],
  },
  {
    id: 78,
    difficulty: "Fácil",
    question:
      "¿Qué snack venezolano hecho con plátano frito se come salado y crujiente?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Tostones / tajadas",
    incorrect_answers: [
      "Papas fritas con salsa tártara",
      "Pretzels",
      "Onion rings",
    ],
  },
  {
    id: 79,
    difficulty: "Fácil",
    question:
      "¿Cuál es un relleno popular para arepas que consiste en pollo desmenuzado con mayonesa o salsa?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Pollo desmechado",
    incorrect_answers: ["Salmón ahumado", "Caviar ruso", "Foie gras"],
  },
  {
    id: 80,
    difficulty: "Fácil",
    question:
      "¿Qué sopa espesa hecha con plátano y carne es típica en algunas regiones de Venezuela?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Mazamorra o sopas a base de plátano",
    incorrect_answers: ["Ramen", "Minestrone", "Borscht"],
  },
  {
    id: 81,
    difficulty: "Fácil",
    question:
      "¿Cuál es la forma de saludo informal muy usada en Venezuela para decir 'hola'?",
    category: charactersAndPopularCulture,
    correct_answer: "Hola / Buenas",
    incorrect_answers: ["Howdy", "Guten Tag", "Ciao bella"],
  },
  {
    id: 82,
    difficulty: "Fácil",
    question:
      "¿Qué tipo de baile se baila en festividades tradicionales venezolanas, especialmente en los llanos?",
    category: charactersAndPopularCulture,
    correct_answer: "Joropo",
    incorrect_answers: ["Ballet clásico", "Tango argentino", "Flamenco"],
  },
  {
    id: 83,
    difficulty: "Fácil",
    question:
      "¿Qué instrumento típico venezolano es similar a una pequeña guitarra y tiene cuatro cuerdas?",
    category: charactersAndPopularCulture,
    correct_answer: "Cuatro",
    incorrect_answers: ["Sitar", "Banjo", "Balalaika"],
  },
  {
    id: 84,
    difficulty: "Fácil",
    question:
      "¿Qué deporte ha tenido históricamente muchos peloteros famosos provenientes de Venezuela?",
    category: charactersAndPopularCulture,
    correct_answer: "Béisbol",
    incorrect_answers: ["Esquí alpino", "Hockey sobre hielo", "Lacrosse"],
  },
  {
    id: 85,
    difficulty: "Fácil",
    question:
      "¿Qué palabra venezolana se usa para decir 'trabajo' en algunos contextos informales (ej. 'chamba')?",
    category: charactersAndPopularCulture,
    correct_answer: "Chamba",
    incorrect_answers: ["Gig (en inglés)", "Shift (en inglés)", "Jobo"],
  },
  {
    id: 86,
    difficulty: "Fácil",
    question:
      "¿Cuál es un popular género musical venezolano que también inspira festividades y bailes?",
    category: charactersAndPopularCulture,
    correct_answer: "Joropo",
    incorrect_answers: ["Techno", "Hard rock", "Grunge"],
  },
  {
    id: 87,
    difficulty: "Fácil",
    question:
      "¿Qué actor o actriz venezolana fue Miss Universo o Miss Mundo (figura conocida de belleza)?",
    category: charactersAndPopularCulture,
    correct_answer:
      "Silueta de ganadoras famosas (ej. hasta la fecha Venezuela ha tenido varias reinas internacionales)",
    incorrect_answers: ["Marilyn Monroe", "Audrey Hepburn", "Grace Kelly"],
  },
  {
    id: 88,
    difficulty: "Fácil",
    question:
      "¿Qué bebida fría a base de frutas es común en puestos callejeros venezolanos?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Jugo natural",
    incorrect_answers: ["Latte macchiato", "Matcha latte", "Kefir de frutas"],
  },
  {
    id: 89,
    difficulty: "Fácil",
    question:
      "¿Qué producto típico que combina maíz y queso se come como snack caliente o en ferias?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Cachapa con queso",
    incorrect_answers: [
      "Pancake con sirope",
      "Scones con crema",
      "Crepe Nutella",
    ],
  },
  {
    id: 90,
    difficulty: "Fácil",
    question:
      "¿Qué costa venezolana es famosa por sus playas con aguas turquesa y cayos (parque nacional)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Morrocoy (Parque Nacional Morrocoy, Falcón)",
    incorrect_answers: ["Cabo de Hornos", "Islas Faroe", "Costa de Amalfi"],
  },
  {
    id: 91,
    difficulty: "Fácil",
    question:
      "¿Cómo se llama el río más largo de Venezuela (uno de los más importantes)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Orinoco",
    incorrect_answers: ["Amazonas", "Nilo", "Mississippi"],
  },
  {
    id: 92,
    difficulty: "Fácil",
    question:
      "¿Qué palabra en Venezuela se usa para referirse a la playa de manera informal (ej. 'playa' común)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Playa",
    incorrect_answers: ["Shoreline", "Strand", "Rivage"],
  },
  {
    id: 93,
    difficulty: "Fácil",
    question:
      "¿Qué ciudad es conocida como 'la tierra de Gracia' y tiene una catedral histórica (estado Nueva Esparta)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Cumaná (apodada 'Tierra de Gracia')",
    incorrect_answers: ["Maracaibo", "Valencia", "Caracas"],
  },
  {
    id: 94,
    difficulty: "Fácil",
    question:
      "¿Qué parque nacional venezolano protege los tepuyes y paisajes únicos (como el Roraima y Auyán-tepui)?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Parque Nacional Canaima",
    incorrect_answers: [
      "Parque Nacional Yellowstone",
      "Parque Nacional Banff",
      "Parque Nacional Kruger",
    ],
  },
  {
    id: 95,
    difficulty: "Fácil",
    question:
      "¿Qué bahía tranquila y turística se encuentra en el estado Nueva Esparta?",
    category: placesAndCitiesOfVenezuela,
    correct_answer:
      "La Bahia de Puerto La Cruz / Islas cercanas (ej. Margarita)",
    incorrect_answers: [
      "Bahía de Hudson",
      "Bahía de Biscayne",
      "Bahía de Fundy",
    ],
  },
  {
    id: 96,
    difficulty: "Fácil",
    question:
      "¿Qué instrumento de viento es común en algunas bandas tradicionales venezolanas?",
    category: charactersAndPopularCulture,
    correct_answer: "Flauta",
    incorrect_answers: ["Didgeridoo", "Bagpipes", "Theremin"],
  },
  {
    id: 97,
    difficulty: "Fácil",
    question:
      "¿Qué famoso conductor de orquesta venezolano estudió en El Sistema y dirige orquestas internacionales?",
    category: charactersAndPopularCulture,
    correct_answer: "Gustavo Dudamel",
    incorrect_answers: ["Andrea Bocelli", "Yo-Yo Ma", "John Williams"],
  },
  {
    id: 98,
    difficulty: "Fácil",
    question:
      "¿Qué palabra venezolana se usa para referirse a 'dinero' de forma coloquial (ej. 'plata')?",
    category: charactersAndPopularCulture,
    correct_answer: "Plata",
    incorrect_answers: ["Beef", "Fruit", "Papel"],
  },
  {
    id: 99,
    difficulty: "Fácil",
    question:
      "¿Qué ciudad venezolana es conocida por su tradición en la industria automotriz y está en el centro del país?",
    category: placesAndCitiesOfVenezuela,
    correct_answer: "Valencia",
    incorrect_answers: ["Porlamar", "Coro", "Tucupita"],
  },
  {
    id: 100,
    difficulty: "Fácil",
    question:
      "¿Cuál es un postre tradicional venezolano que se sirve en forma de flan y es muy popular en celebraciones?",
    category: venezuelanFoodsAndFlavors,
    correct_answer: "Quesillo",
    incorrect_answers: ["Tarta de manzana", "Brownie de chocolate", "Pavlova"],
  },
];

// export const questions = [
//   {
//     id: 1,
//     difficulty: "Fácil",
//     question: "¿Qué evento inició la Primera Guerra Mundial?",
//     category: historia,
//     correct_answer: "El asesinato del Archiduque Franz Ferdinand de Austria",
//     incorrect_answers: [
//       "El hundimiento del Titanic",
//       "La invasión de Polonia por Alemania",
//       "La Revolución Francesa",
//     ],
//   },
//   {
//     id: 2,
//     difficulty: "Fácil",
//     question: '¿Quién es el autor de "Cien años de soledad"?        ',
//     category: literatura,
//     correct_answer: "Gabriel García Márquez",
//     incorrect_answers: ["Julio Cortázar", "Mario Vargas Llosa", "Pablo Neruda"],
//   },
//   {
//     id: 3,
//     difficulty: "Fácil",
//     question: "¿En qué deporte se utiliza un disco?",
//     category: deportes,
//     correct_answer: "Hockey sobre hielo",
//     incorrect_answers: ["Fútbol", "Baloncesto", "Béisbol"],
//   },
//   {
//     id: 4,
//     difficulty: "Medio",
//     question: "¿Qué sustancia es conocida como la 'molécula de la vida'?",
//     category: ciencia,
//     correct_answer: "El ADN",
//     incorrect_answers: ["La glucosa", "La insulina", "La proteína"],
//   },
//   {
//     id: 5,
//     difficulty: "Difícil",
//     question: "¿Quién es considerado el padre de la filosofía occidental?",
//     category: filosofia,
//     correct_answer: "Sócrates",
//     incorrect_answers: ["Aristóteles", "Platón", "Nietzsche"],
//   },
//   {
//     id: 6,
//     difficulty: "Medio",
//     question: "¿En qué año fue fundada la compañía Apple?",
//     category: tecnologia,
//     correct_answer: "1976",
//     incorrect_answers: ["1984", "1991", "1967"],
//   },
//   {
//     id: 7,
//     difficulty: "Fácil",
//     question: "¿Cuál es el río más largo del mundo?",
//     category: geografia,
//     correct_answer: "El Río Amazonas",
//     incorrect_answers: ["El Río Nilo", "El Río Yangtze", "El Río Misisipi"],
//   },
//   {
//     id: 8,
//     difficulty: "Medio",
//     question: "¿Cuál es el océano más grande del mundo?",
//     category: geografia,
//     correct_answer: "El Océano Pacífico",
//     incorrect_answers: [
//       "El Océano Atlántico",
//       "El Océano Índico",
//       "El Océano Ártico",
//     ],
//   },
//   {
//     id: 9,
//     difficulty: "Difícil",
//     question: "¿Cuál es la obra más famosa de William Shakespeare?",
//     category: literatura,
//     correct_answer: "Hamlet",
//     incorrect_answers: ["Romeo y Julieta", "Macbeth", "El Rey Lear"],
//   },
//   {
//     id: 10,
//     difficulty: "Medio",
//     question: "¿Qué es lo que se mide con la escala de Richter?",
//     category: ciencia,
//     correct_answer: "La magnitud de los terremotos",
//     incorrect_answers: [
//       "La velocidad del sonido",
//       "La intensidad de los huracanes",
//       "La temperatura en grados Fahrenheit",
//     ],
//   },
//   {
//     id: 11,
//     difficulty: "Fácil",
//     question: "¿Qué país ganó el primer Mundial de Fútbol?",
//     category: deportes,
//     correct_answer: "Uruguay",
//     incorrect_answers: ["Brasil", "Argentina", "Alemania"],
//   },
//   {
//     id: 12,
//     difficulty: "Medio",
//     question: "¿Qué es el efecto invernadero?",
//     category: ciencia,
//     correct_answer: "Un fenómeno atmosférico que retiene el calor en la Tierra",
//     incorrect_answers: [
//       "Un tipo de casa de vidrio para plantas",
//       "Un proceso químico para conservar alimentos",
//       "Un tipo de sistema de calefacción para edificios",
//     ],
//   },
//   {
//     id: 13,
//     difficulty: "Medio",
//     question:
//       "¿En qué año se celebraron los primeros Juegos Olímpicos modernos?",
//     category: deportes,
//     correct_answer: "1896",
//     incorrect_answers: ["1900", "1924", "1936"],
//   },
//   {
//     id: 14,
//     difficulty: "Fácil",
//     question: "¿Cuál es el planeta más grande del sistema solar?",
//     category: ciencia,
//     correct_answer: "Júpiter",
//     incorrect_answers: ["Saturno", "Neptuno", "Urano"],
//   },
//   {
//     id: 15,
//     difficulty: "Fácil",
//     question: "¿Quién escribió la obra 'Don Quijote de la Mancha'?",
//     category: literatura,
//     correct_answer: "Miguel de Cervantes",
//     incorrect_answers: [
//       "Federico García Lorca",
//       "Gabriel García Márquez",
//       "Pablo Neruda",
//     ],
//   },
//   {
//     id: 16,
//     difficulty: "Medio",
//     question: "¿Cuál es el elemento químico más abundante en la Tierra?",
//     category: ciencia,
//     correct_answer: "Oxígeno",
//     incorrect_answers: ["Nitrógeno", "Hierro", "Silicio"],
//   },
//   {
//     id: 17,
//     difficulty: "Medio",
//     question: "¿Cuál es el país más poblado del mundo?",
//     category: geografia,
//     correct_answer: "China",
//     incorrect_answers: ["India", "Estados Unidos", "Brasil"],
//   },
//   {
//     id: 18,
//     difficulty: "Medio",
//     question: "¿Quién es considerado el padre de la filosofía occidental?",
//     category: filosofia,
//     correct_answer: "Sócrates",
//     incorrect_answers: ["Platón", "Aristóteles", "Descartes"],
//   },
//   {
//     id: 19,
//     difficulty: "Difícil",
//     question: "¿Qué científico propuso la teoría del Big Bang?",
//     category: ciencia,
//     correct_answer: "Georges Lemaître",
//     incorrect_answers: ["Albert Einstein", "Stephen Hawking", "Isaac Newton"],
//   },
//   {
//     id: 20,
//     difficulty: "Fácil",
//     question: '¿Quién es el autor de la novela "El viejo y el mar"?',
//     category: literatura,
//     correct_answer: "Ernest Hemingway",
//     incorrect_answers: [
//       "William Shakespeare",
//       "J.K. Rowling",
//       "F. Scott Fitzgerald",
//     ],
//   },
//   {
//     id: 21,
//     difficulty: "Fácil",
//     question: "¿Cuál es el órgano más grande del cuerpo humano?",
//     category: ciencia,
//     correct_answer: "La piel",
//     incorrect_answers: ["El hígado", "El corazón", "Los pulmones"],
//   },
//   {
//     id: 22,
//     difficulty: "Medio",
//     question: "¿Quién es el creador del sistema operativo Linux?",
//     category: tecnologia,
//     correct_answer: "Linus Torvalds",
//     incorrect_answers: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg"],
//   },
//   {
//     id: 23,
//     difficulty: "Medio",
//     question: "¿En qué año terminó la Segunda Guerra Mundial?",
//     category: historia,
//     correct_answer: "1945",
//     incorrect_answers: ["1939", "1941", "1943"],
//   },
//   {
//     id: 24,
//     difficulty: "Fácil",
//     question: "¿Cuál es el planeta más cercano al Sol?",
//     category: ciencia,
//     correct_answer: "Mercurio",
//     incorrect_answers: ["Venus", "Marte", "Júpiter"],
//   },
//   {
//     id: 25,
//     difficulty: "Medio",
//     question:
//       "¿Qué escritor es conocido por haber escrito 'Cien años de soledad'?",
//     category: literatura,
//     correct_answer: "Gabriel García Márquez",
//     incorrect_answers: ["Jorge Luis Borges", "Pablo Neruda", "Julio Cortázar"],
//   },
//   {
//     id: 26,
//     difficulty: "Difícil",
//     question: "¿Qué país es el más grande en términos de superficie terrestre?",
//     category: geografia,
//     correct_answer: "Rusia",
//     incorrect_answers: ["Estados Unidos", "China", "Australia"],
//   },
//   {
//     id: 27,
//     difficulty: "Medio",
//     question: "¿Cuál es la capital de Canadá?",
//     category: geografia,
//     correct_answer: "Ottawa",
//     incorrect_answers: ["Toronto", "Montreal", "Vancouver"],
//   },
//   {
//     id: 28,
//     difficulty: "Fácil",
//     question: "¿Qué elemento químico tiene el símbolo H?",
//     category: ciencia,
//     correct_answer: "Hidrógeno",
//     incorrect_answers: ["Helio", "Hierro", "Hormigón"],
//   },
//   {
//     id: 29,
//     difficulty: "Medio",
//     question:
//       "¿Qué jugador de fútbol ha ganado más Balones de Oro en la historia?",
//     category: deportes,
//     correct_answer: "Lionel Messi",
//     incorrect_answers: ["Cristiano Ronaldo", "Johan Cruyff", "Diego Maradona"],
//   },
//   {
//     id: 30,
//     difficulty: "Fácil",
//     question: "¿En qué año ocurrió la Revolución Francesa?",
//     category: historia,
//     correct_answer: "1789",
//     incorrect_answers: ["1848", "1917", "1492"],
//   },
//   // -------------------
//   {
//     id: 31,
//     difficulty: "Fácil",
//     category: tecnologia,
//     question: "¿Qué significa la sigla HTML?",
//     correct_answer: "HyperText Markup Language",
//     incorrect_answers: [
//       "Hyperlinks and Text Markup Language",
//       "Home Tool Markup Language",
//       "Hyperlinking Text Markup Language",
//     ],
//   },
//   {
//     id: 32,
//     difficulty: "Fácil",
//     category: tecnologia,
//     question: "¿Cuál es el navegador web más utilizado en el mundo?",
//     correct_answer: "Google Chrome",
//     incorrect_answers: ["Safari", "Firefox", "Internet Explorer"],
//   },
//   {
//     id: 33,
//     difficulty: "Fácil",
//     category: tecnologia,
//     question:
//       "¿Qué lenguaje de programación es más utilizado para el desarrollo web?",
//     correct_answer: "JavaScript",
//     incorrect_answers: ["Python", "Java", "C++"],
//   },
//   {
//     id: 34,
//     difficulty: "Medio",
//     category: tecnologia,
//     question: "¿Qué es un servidor web?",
//     correct_answer: "Un programa que recibe y procesa solicitudes HTTP",
//     incorrect_answers: [
//       "Un programa que envía correos electrónicos",
//       "Un programa que protege la privacidad de los usuarios en línea",
//       "Un programa que realiza operaciones matemáticas complejas",
//     ],
//   },
//   {
//     id: 35,
//     difficulty: "Medio",
//     category: tecnologia,
//     question: "¿Qué es un ataque de phishing?",
//     correct_answer:
//       "Un intento de obtener información confidencial a través de un correo electrónico falso",
//     incorrect_answers: [
//       "Un virus que daña los archivos del ordenador",
//       "Un tipo de ataque DDoS",
//       "Un intento de secuestrar el tráfico de internet",
//     ],
//   },
//   {
//     id: 36,
//     difficulty: "Medio",
//     category: tecnologia,
//     question: "¿Qué es un archivo CSV?",
//     correct_answer: "Un archivo de texto con valores separados por comas",
//     incorrect_answers: [
//       "Un archivo de audio comprimido",
//       "Un archivo de imagen en formato vectorial",
//       "Un archivo de vídeo de alta definición",
//     ],
//   },
//   {
//     id: 37,
//     difficulty: "Difícil",
//     category: tecnologia,
//     question: "¿Qué es un algoritmo de cifrado asimétrico?",
//     correct_answer: "Un método de cifrado que utiliza dos claves diferentes",
//     incorrect_answers: [
//       "Un método de cifrado que utiliza la misma clave para cifrar y descifrar",
//       "Un método de cifrado que no utiliza claves",
//       "Un método de cifrado que solo se utiliza en aplicaciones militares",
//     ],
//   },
//   {
//     id: 38,
//     difficulty: "Difícil",
//     category: tecnologia,
//     question: "¿Qué es una red privada virtual (VPN)?",
//     correct_answer:
//       "Una conexión segura a una red privada a través de internet",
//     incorrect_answers: [
//       "Una red de computadoras en una organización",
//       "Una red de computadoras conectadas a internet",
//       "Una red de computadoras que solo utiliza tecnología inalámbrica",
//     ],
//   },
//   {
//     id: 39,
//     difficulty: "Difícil",
//     question: "¿En qué año se produjo la Guerra de los Cien Años?",
//     category: historia,
//     correct_answer: "1337",
//     incorrect_answers: ["1066", "1415", "1642"],
//   },
//   {
//     id: 40,
//     difficulty: "Fácil",
//     question: "¿En qué año se produjo el ataque a Pearl Harbor?",
//     category: historia,
//     correct_answer: "1941",
//     incorrect_answers: ["1939", "1942", "1945"],
//   },
//   {
//     id: 41,
//     difficulty: "Medio",
//     question: "¿Qué tratado dio fin a la Primera Guerra Mundial?",
//     category: historia,
//     correct_answer: "Tratado de Versalles",
//     incorrect_answers: [
//       "Tratado de Tordesillas",
//       "Tratado de Westfalia",
//       "Tratado de Nankín",
//     ],
//   },
//   {
//     id: 42,
//     difficulty: "Difícil",
//     question: "¿Quién fue el último emperador de la Dinastía Qing en China?",
//     category: historia,
//     correct_answer: "Puyi",
//     incorrect_answers: ["Hongwu", "Wuzong", "Kangxi"],
//   },
//   {
//     id: 43,
//     difficulty: "Fácil",
//     question:
//       "¿Cuál fue el nombre de la primera expedición de Cristóbal Colón?",
//     category: historia,
//     correct_answer: "La Santa María",
//     incorrect_answers: ["La Pinta", "La Niña", "La Santísima Trinidad"],
//   },
//   {
//     id: 44,
//     difficulty: "Medio",
//     question:
//       "¿Cuál fue el primer país en enviar un objeto hecho por el hombre a la luna?",
//     category: historia,
//     correct_answer: "Estados Unidos",
//     incorrect_answers: ["Unión Soviética", "China", "Japón"],
//   },
//   {
//     id: 45,
//     difficulty: "Difícil",
//     question:
//       "¿Cuál fue la primera ciudad en el mundo en tener una población de más de un millón de habitantes?",
//     category: historia,
//     correct_answer: "Roma",
//     incorrect_answers: ["Atenas", "Babilonia", "Nínive"],
//   },
//   {
//     id: 46,
//     difficulty: "Fácil",
//     question: "¿Quién fue el primer presidente de los Estados Unidos?",
//     category: historia,
//     correct_answer: "George Washington",
//     incorrect_answers: [
//       "Thomas Jefferson",
//       "Abraham Lincoln",
//       "Franklin D. Roosevelt",
//     ],
//   },
//   {
//     id: 47,
//     difficulty: "Medio",
//     question: "¿Cuál fue la primera dinastía en gobernar en China?",
//     category: historia,
//     correct_answer: "Xia",
//     incorrect_answers: ["Han", "Tang", "Song"],
//   },
//   {
//     id: 48,
//     difficulty: "Fácil",
//     question: '¿Quién escribió la obra "Don Quijote de la Mancha"?',
//     category: literatura,
//     correct_answer: "Miguel de Cervantes",
//     incorrect_answers: [
//       "Gabriel García Márquez",
//       "Jorge Luis Borges",
//       "Pablo Neruda",
//     ],
//   },
//   {
//     id: 49,
//     difficulty: "Medio",
//     question:
//       "¿Cuál de las siguientes novelas es escrita por Gabriel García Márquez?",
//     category: literatura,
//     correct_answer: "Cien años de soledad",
//     incorrect_answers: [
//       "Rayuela",
//       "La ciudad y los perros",
//       "La casa de los espíritus",
//     ],
//   },
//   {
//     id: 50,
//     difficulty: "Difícil",
//     question: '¿Quién escribió "La metamorfosis"?',
//     category: literatura,
//     correct_answer: "Franz Kafka",
//     incorrect_answers: ["Virginia Woolf", "James Joyce", "F. Scott Fitzgerald"],
//   },
//   {
//     id: 51,
//     difficulty: "Fácil",
//     question: '¿Quién escribió "El retrato de Dorian Gray"?',
//     category: literatura,
//     correct_answer: "Oscar Wilde",
//     incorrect_answers: ["Edgar Allan Poe", "Emily Bronte", "Charles Dickens"],
//   },
//   {
//     id: 52,
//     difficulty: "Medio",
//     question:
//       "¿Cuál de las siguientes obras no fue escrita por William Shakespeare?",
//     category: literatura,
//     correct_answer: "Moby Dick",
//     incorrect_answers: ["Hamlet", "Macbeth", "Otelo"],
//   },
//   {
//     id: 53,
//     difficulty: "Difícil",
//     question:
//       "¿Cuál de las siguientes obras de José Saramago recibió el Premio Nobel de Literatura?",
//     category: literatura,
//     correct_answer: "Ensayo sobre la ceguera",
//     incorrect_answers: [
//       "La caverna",
//       "El evangelio según Jesucristo",
//       "Las intermitencias de la muerte",
//     ],
//   },
//   {
//     id: 54,
//     difficulty: "Fácil",
//     question: '¿Quién escribió la novela "El guardián entre el centeno"?',
//     category: literatura,
//     correct_answer: "J.D. Salinger",
//     incorrect_answers: [
//       "F. Scott Fitzgerald",
//       "Ernest Hemingway",
//       "Tennessee Williams",
//     ],
//   },
//   {
//     id: 55,
//     difficulty: "Difícil",
//     question: "¿Cuál es el país más grande de África?",
//     category: geografia,
//     correct_answer: "Argelia",
//     incorrect_answers: ["Sudán", "Libia", "República Democrática del Congo"],
//   },
//   {
//     id: 56,
//     difficulty: "Fácil",
//     question: "¿Cuál es el país más grande del mundo?",
//     category: geografia,
//     correct_answer: "Rusia",
//     incorrect_answers: ["China", "Estados Unidos", "Canadá"],
//   },
//   {
//     id: 57,
//     difficulty: "Medio",
//     question: "¿En qué continente se encuentra el lago Baikal?",
//     category: geografia,
//     correct_answer: "Asia",
//     incorrect_answers: ["Europa", "África", "América del Sur"],
//   },
//   {
//     id: 58,
//     difficulty: "Medio",
//     question: "¿Cuál es el país más poblado del mundo?",
//     category: geografia,
//     correct_answer: "China",
//     incorrect_answers: ["India", "Estados Unidos", "Indonesia"],
//   },
//   {
//     id: 59,
//     difficulty: "Difícil",
//     question: "¿Cuál es la montaña más alta del mundo?",
//     category: geografia,
//     correct_answer: "El Monte Everest",
//     incorrect_answers: ["El K2", "El Mont Blanc", "El Aconcagua"],
//   },
//   {
//     id: 60,
//     difficulty: "Difícil",
//     question: "¿Cuál es el país más pequeño del mundo?",
//     category: geografia,
//     correct_answer: "El Vaticano",
//     incorrect_answers: ["Mónaco", "Nauru", "Tuvalu"],
//   },
//   {
//     id: 61,
//     difficulty: "Medio",
//     question: "¿Cuál es el país más extenso de África?",
//     category: geografia,
//     correct_answer: "Argelia",
//     incorrect_answers: ["Nigeria", "Egipto", "Sudáfrica"],
//   },
//   {
//     id: 62,
//     difficulty: "Fácil",
//     question: "¿Qué país ganó la Copa Mundial de la FIFA en 2018?",
//     category: deportes,
//     correct_answer: "Francia",
//     incorrect_answers: ["Alemania", "Brasil", "Argentina"],
//   },
//   {
//     id: 63,
//     difficulty: "Fácil",
//     question: "¿Qué deporte se juega en Wimbledon?",
//     category: deportes,
//     correct_answer: "Tenis",
//     incorrect_answers: ["Golf", "Fútbol", "Rugby"],
//   },
//   {
//     id: 64,
//     difficulty: "Medio",
//     question: "¿Cuántos puntos vale un touchdown en el fútbol americano?",
//     category: deportes,
//     correct_answer: "6",
//     incorrect_answers: ["4", "7", "5"],
//   },
//   {
//     id: 65,
//     difficulty: "Medio",
//     question:
//       "¿Cuál es el jugador de baloncesto con más anillos de campeonato en la NBA?",
//     category: deportes,
//     correct_answer: "Bill Russell",
//     incorrect_answers: [
//       "Michael Jordan",
//       "Kareem Abdul-Jabbar",
//       "LeBron James",
//     ],
//   },
//   {
//     id: 66,
//     difficulty: "Medio",
//     question: "¿Cuál es el país de origen del futbolista Lionel Messi?",
//     category: deportes,
//     correct_answer: "Argentina",
//     incorrect_answers: ["Brasil", "España", "Portugal"],
//   },
//   {
//     id: 67,
//     difficulty: "Difícil",
//     question: "¿En qué año se celebraron los Juegos Olímpicos de Beijing?",
//     category: deportes,
//     correct_answer: "2008",
//     incorrect_answers: ["2012", "2004", "2016"],
//   },
//   {
//     id: 68,
//     difficulty: "Difícil",
//     question:
//       "¿Quién es el máximo goleador en la historia de la Liga Española?",
//     category: deportes,
//     correct_answer: "Lionel Messi",
//     incorrect_answers: ["Cristiano Ronaldo", "Telmo Zarra", "Hugo Sánchez"],
//   },
//   {
//     id: 69,
//     difficulty: "Difícil",
//     question: '¿En qué deporte se utiliza el término "smash"?',
//     category: deportes,
//     correct_answer: "Bádminton",
//     incorrect_answers: ["Voleibol", "Tenis", "Squash"],
//   },
//   {
//     id: 70,
//     category: filosofia,
//     difficulty: "Fácil",
//     question: "¿Cuál es la obra más conocida de Platón?",
//     correct_answer: "La República",
//     incorrect_answers: ["El Banquete", "Timeo", "Fedón"],
//   },
//   {
//     id: 71,
//     category: filosofia,
//     difficulty: "Medio",
//     question: "¿Cuál es el concepto central de la filosofía de Descartes?",
//     correct_answer: "El cogito ergo sum",
//     incorrect_answers: ["El empirismo", "El materialismo", "La fenomenología"],
//   },
//   {
//     id: 72,
//     category: filosofia,
//     difficulty: "Difícil",
//     question: "¿Qué es la dialéctica en la filosofía de Hegel?",
//     correct_answer:
//       "El método para llegar a la verdad mediante la contradicción",
//     incorrect_answers: [
//       "La creación de un sistema filosófico",
//       "La negación de la realidad",
//       "El análisis de los procesos cognitivos",
//     ],
//   },
//   {
//     id: 73,
//     category: filosofia,
//     difficulty: "Medio",
//     question: "¿Qué es el nihilismo en la filosofía?",
//     correct_answer: "La negación de todos los valores y creencias",
//     incorrect_answers: [
//       "La afirmación de la existencia de un ser superior",
//       "La creencia en la reencarnación",
//       "La negación de la existencia del mundo externo",
//     ],
//   },
//   {
//     id: 74,
//     category: filosofia,
//     difficulty: "Difícil",
//     question: "¿Qué es la deconstrucción en la filosofía de Jacques Derrida?",
//     correct_answer:
//       "El análisis crítico de la relación entre los significados y los conceptos",
//     incorrect_answers: [
//       "La creación de nuevos conceptos a partir de la combinación de los antiguos",
//       "La búsqueda de la verdad absoluta",
//       "La negación de la existencia del lenguaje",
//     ],
//   },
//   {
//     id: 75,
//     category: filosofia,
//     difficulty: "Fácil",
//     question: "¿Qué es la ética?",
//     correct_answer:
//       "La rama de la filosofía que estudia la moral y la conducta humana",
//     incorrect_answers: [
//       "La rama de la filosofía que estudia la lógica",
//       "La rama de la filosofía que estudia la mente",
//       "La rama de la filosofía que estudia el conocimiento",
//     ],
//   },
//   {
//     id: 76,
//     category: filosofia,
//     difficulty: "Medio",
//     question: "¿Qué es el imperativo categórico en la filosofía de Kant?",
//     correct_answer: "La regla moral que se debe seguir en cualquier situación",
//     incorrect_answers: [
//       "La creencia en la existencia de un Dios creador",
//       "La negación de la libertad humana",
//       "La afirmación de la existencia de una verdad absoluta",
//     ],
//   },
//   {
//     id: 77,
//     difficulty: "Fácil",
//     question: '¿Quién fue el autor de la obra "La República"?',
//     category: filosofia,
//     correct_answer: "Platón",
//     incorrect_answers: ["Aristóteles", "Sócrates", "Nietzsche"],
//   },
//   {
//     id: 78,
//     difficulty: "Medio",
//     question:
//       "¿Cuál es el término filosófico para referirse al estudio del conocimiento?",
//     category: filosofia,
//     correct_answer: "Epistemología",
//     incorrect_answers: ["Ontología", "Metafísica", "Lógica"],
//   },
//   {
//     id: 79,
//     difficulty: "Difícil",
//     question:
//       '¿Quién escribió el libro "El mundo como voluntad y representación"?',
//     category: filosofia,
//     correct_answer: "Arthur Schopenhauer",
//     incorrect_answers: [
//       "Friedrich Nietzsche",
//       "Immanuel Kant",
//       "Jean-Paul Sartre",
//     ],
//   },
//   {
//     id: 80,
//     difficulty: "Difícil",
//     question: "¿Cuál es la partícula subatómica más pesada?",
//     category: ciencia,
//     correct_answer: "Quark top",
//     incorrect_answers: ["Electrón", "Protón", "Neutrón"],
//   },
//   {
//     id: 81,
//     category: ciencia,
//     difficulty: "Medio",
//     question: "¿Qué es la capa de ozono?",
//     correct_answer:
//       "Una capa de gas que protege la Tierra de la radiación ultravioleta del sol",
//     incorrect_answers: [
//       "Una capa de nubes en la atmósfera",
//       "La capa más externa de la Tierra",
//       "Una capa de gases que produce el efecto invernadero",
//     ],
//   },
//   {
//     id: 82,
//     category: ciencia,
//     difficulty: "Difícil",
//     question: "¿Qué es la antimateria?",
//     correct_answer:
//       "Una forma de materia que tiene propiedades opuestas a la materia ordinaria",
//     incorrect_answers: [
//       "Una forma de materia que no tiene carga eléctrica",
//       "Una forma de materia que no tiene masa",
//       "Una forma de energía que tiene la capacidad de desintegrar la materia",
//     ],
//   },
//   {
//     id: 83,
//     difficulty: "Fácil",
//     question: '¿Qué es el acrónimo "CPU" en inglés?',
//     category: tecnologia,
//     correct_answer: "Central Processing Unit",
//     incorrect_answers: [
//       "Computer Personal Unit",
//       "Central Personal Unit",
//       "Computer Processing Unit",
//     ],
//   },
//   {
//     id: 84,
//     difficulty: "Medio",
//     question:
//       "¿Cuál es el nombre de la primera computadora electrónica digital?",
//     category: tecnologia,
//     correct_answer: "ENIAC",
//     incorrect_answers: ["UNIVAC", "COLOSSUS", "EDSAC"],
//   },
// ];
